### ISSUE TITLE
Unable to use the provider to create user with hashed passwords

### ISSUE THREAD

**Issue by pratikmallya** [okta/okta-sdk-golang#102]
The API for creating a user with a hashed password is documented here: 

https://developer.okta.com/docs/reference/api/users/#create-user-with-imported-hashed-password

Example reproduced here:
```
curl -v -X POST \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "Authorization: SSWS ${api_token}" \
-d '{
  "profile": {
    "firstName": "Isaac",
    "lastName": "Brock",
    "email": "isaac.brock@example.com",
    "login": "isaac.brock@example.com",
    "mobilePhone": "555-415-1337"
  },
  "credentials": {
    "password" : {
      "hash": {
        "algorithm": "BCRYPT",
        "workFactor": 10,
        "salt": "rwh3vH166HCH/NT9XV5FYu",
        "value": "qaMqvAPULkbiQzkTCWo5XDcvzpk8Tna"
      }
    }
  }
}' "https://${yourOktaDomain}/api/v1/users?activate=false"
```

However, it appears that the [PassWordCredentials](https://godoc.org/github.com/okta/okta-sdk-golang/okta#PasswordCredential) struct  does not support passing in the hash values, only the password.

Could support be added for this api to the sdk?

**Comment by bretterer** [comment]
@pratikmallya Thank you for this feedback.  I have just tagged a release candidate for 2.0.0, https://github.com/okta/okta-sdk-golang/releases/tag/v2.0.0-rc.1 which includes a `okta.v2/passwordCredential.go` update to include a `[Hash](okta.v2/passwordCredentialHash.go)`

Please check out the new tag and see if this resolved what you are looking to do

**Comment by bretterer** [comment]
Closing this as stale.  If you are still experiencing an issue, please feel free to open a new issue and we will get back to you.
