### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by klauern** [okta/okta-sdk-golang#111]
A list of issues I've stumbled on, which lead me to believe this project has died:

* 404's in the README in multiple places
* `Makefile` clones non-existent repos
* Travis builds are all failing
* A dozen PR's without any activity
* Last commit made to `master` was from September of last year
* Travis is building off of Go `1.12` and `tip`

So I have a lot of concerns about whether it's worth the effort to continue trying to get something working with this, or just move on and write a cheap wrapper around the REST API.

**Comment by jamesgoodhouse** [comment]
I opened a PR back in January and haven't heard a peep from anyone. Might be worth reaching out to support to get things moving with this repo.

**Comment by chrismorris-okta** [comment]
@klauern Thanks for sharing the list of issues.  

Yes, this repo is still active. We just released OAuth support this month. We have several new releases planned in the coming months. I'm going to go ahead and close this issue but we'll look into addressing some of those issues you raised in our upcoming releases.

**Comment by johanbrandhorst** [comment]
I almost opened another issue exactly like this. I think it might be better to leave this issue open for clear communication to users, since the state of the repo is still pretty bad. When the proper changes and updates have been made we can close it.
