### ISSUE TITLE
running generator locally

### ISSUE THREAD

**Issue by goblain** [okta/okta-sdk-golang#117]
when running `make build` I get 

    yarn run v1.22.4
    $ okta-sdk-generator -t generator -o ../
    /bin/sh: 1: okta-sdk-generator: not found

and it looks like the script is indeed missing from the repo. Am I just confusing things or is there a missing piece to actually run generator after cloning the repo ?

**Comment by bretterer** [comment]
@goblain within the `openapi` folder, did you run `yarn install`?  This is required so you can get our generator tool

However, is there a reason you need to run `make build`, the repo should have everything you need already built

**Comment by goblain** [comment]
yea, the reason is that this sdk is a royal pain to use and I wanted to make some fixes, had to make some workaround in the meantime so no longer relevant
