### ISSUE TITLE
Use official generated Go file header

### ISSUE THREAD

**Issue by johanbrandhorst** [okta/okta-sdk-golang#118]
The format for a header that can identify any generated Go file was decided in https://github.com/golang/go/issues/13560#issuecomment-288457920. The current generated files do not conform to this. We should change the generated code to output in this format.

I intend to submit a PR to fix this.

**Comment by bretterer** [comment]
Thanks for the information here.  We will update our headers in the templates and release a new tag of the SDK

Internal Ref: OKTA-331907
