### ISSUE TITLE
Don't panic on simple configuration errors

### ISSUE THREAD

**Issue by johanbrandhorst** [okta/okta-sdk-golang#122]
The okta.NewClient method panics on any configuration validation errors, instead of returning the error itself. This is an undesirable property of a library, and I propose changing it to return the error to the user instead.

The offending line is here:
https://github.com/okta/okta-sdk-golang/blob/master/openapi/generator/templates/okta.go.hbs#L61.

I intend to submit a PR to fix this. It is also present on the v2 branch: https://github.com/okta/okta-sdk-golang/blob/sdk_v2/openapi.v2/generator/templates/okta.go.hbs#L61

**Comment by bretterer** [comment]
Thank you for the report here. We will be investigating this for a potential way of addressing this.

Internal Ref: OKTA-331910

**Comment by hafuta** [comment]
+1 
Same here, it panics because of minor issues such as domain containing `-admin`, the `NewClient` function is returning error, I don't see any reason to use `panic` in case of validation errors.
