### ISSUE TITLE
Nil pointer dereference in requestExecutor.go

### ISSUE THREAD

**Issue by johanbrandhorst** [okta/okta-sdk-golang#125]
Hi!

I ran into a panic in testing which I think can happen in real code as well:
```
github.com/okta/okta-sdk-golang/okta.(*RequestExecutor).doWithRetries(0xc0001bc0c0, 0xc00010cc00, 0x0, 0x5e99cf2e, 0x0, 0xc0000f7b88, 0xf, 0xc0001dc100)
	/home/circleci/.go_workspace/pkg/mod/github.com/okta/okta-sdk-golang@v1.1.0/okta/requestExecutor.go:245 +0x225
github.com/okta/okta-sdk-golang/okta.(*RequestExecutor).Do(0xc0001bc0c0, 0xc00010cc00, 0xd0f420, 0xc0001a1a20, 0x0, 0x0, 0x0)
	/home/circleci/.go_workspace/pkg/mod/github.com/okta/okta-sdk-golang@v1.1.0/okta/requestExecutor.go:198 +0x34d
```

The offending code is here:
https://github.com/okta/okta-sdk-golang/blob/master/okta/requestExecutor.go#L245

The issue is that `resp` can sometimes be nil in this case. Clearly, this is already considered on the lines above:

https://github.com/okta/okta-sdk-golang/blob/master/okta/requestExecutor.go#L238-L243

The fix should be to move this logic into the if case.

This bug is also present in the v2 release:

https://github.com/okta/okta-sdk-golang/blob/sdk_v2/okta.v2/requestExecutor.go#L272

I intend to submit a fix for this.

**Comment by bretterer** [comment]
This will be addressed in `v2.0.0-rc.4`. Thank you @johanbrandhorst for the fix.  I implemented it outside of the PR during some other updates.
