### ISSUE TITLE
Unable to use okta-sdk-golang V2 

### ISSUE THREAD

**Issue by bandikishores** [okta/okta-sdk-golang#127]
The [Getting Started](https://github.com/okta/okta-sdk-golang#getting-started) Documentation Suggests using V2 version of SDK and 1.x is deprecated.
However it looks like V2 version is unavailable.

> 
> To install the Okta Golang SDK in your project:
> 
> Version 2.x run go get github.com/okta/okta-sdk-golang/okta.v2
> 
> Version 1.x (Deprecated) run go get github.com/okta/okta-sdk-golang/okta

```
go: finding github.com/okta/okta-sdk-golang/okta.v2 latest
go get github.com/okta/okta-sdk-golang/okta.v2: module github.com/okta/okta-sdk-golang@upgrade found (v1.1.0), but does not contain package github.com/okta/okta-sdk-golang/okta.v2
```

Is the V2 Version available for use or should we go with V1?

**Comment by edulop91** [comment]
You might be able to use it by changing the import path to `"github.com/okta/okta-sdk-golang/v2/okta`

**Comment by bandikishores** [comment]
@edulop91 Ah, Thanks. Can't believe I missed this. I'll keep the ticket open for documentation correction then.

**Comment by bretterer** [comment]
@bandikishores thanks!  We are working on releasing v2.  while it is in `rc` status, things may change a bit, so you should not expect the API to be defined fully. I will make sure we update the `go get` command to use, but yes, you would want to use `github.com/okta/okta-sdk-golang/v2` for your imports

**Comment by oorahduc** [comment]
> @bandikishores thanks! We are working on releasing v2. while it is in `rc` status, things may change a bit, so you should not expect the API to be defined fully. I will make sure we update the `go get` command to use, but yes, you would want to use `github.com/okta/okta-sdk-golang/v2` for your imports

`go get github.com/okta/okta-sdk-golang/v2
package github.com/okta/okta-sdk-golang/v2: cannot find package "github.com/okta/okta-sdk-golang/v2" in any of:
	/Users/oorahduc/.gvm/gos/go1.14.3/src/github.com/okta/okta-sdk-golang/v2 (from $GOROOT)
	/Users/oorahduc/code/go/src/github.com/okta/okta-sdk-golang/v2 (from $GOPATH)
`

I have tried `github.com/okta/okta-sdk-golang/v2`, `github.com/okta/okta-sdk-golang/okta.v2`, `github.com/okta/okta-sdk-golang`, all with the same outcome. Am I missing something?

**Comment by rizkyekoputra** [comment]
same here, got error when doing go get

**Comment by bretterer** [comment]
@oorahduc @rizkyekoputra Thanks for reporting this.  I will take a look at this today.  I am not sure what is happening at the moment as I have not been able to reproduce this issue

**Comment by bretterer** [comment]
@oorahduc @rizkyekoputra Can you both try using `go.mod` instead of `go get`?

```

module bretterer.com/test

require (
        github.com/okta/okta-sdk-golang/v2 v2.0.0
)

go 1.14
```

This works for me and may be the best way at this point for v2 of the sdk.  If this works for you, I will update docs to reflect this.

**Comment by rizkyekoputra** [comment]
@bretterer Already use go.mod for development, but I still need using `go get` for CI purpose on GitLab, cause my app will download all app dependencies which is got an error on go get okta v2

**Comment by bretterer** [comment]
@rizkyekoputra I have still not been able to reproduce the issue when doing `go get github.com/okta/okta-sdk-golang/v2`.  I know there are known issues with semver and using `go get` which is why we opted to support `go mod` which should work fine with CI.  As long as you have access to go mod which you do in go11+, you should be able to tell your CI to do `go mod download` which will create a vendor folder for you.

**Comment by bretterer** [comment]
Closing this as stale.  If you are still experiencing an issue, please feel free to open a new issue and we will get back to you.

**Comment by grantjoy** [comment]
This is still an issue. The instructions in the README are broken and the instructions on this ticket fixed it for me.
