### ISSUE TITLE
Email register not received

### ISSUE THREAD

**Issue by rizkyekoputra** [okta/okta-sdk-golang#130]
Hi, I try to create new user with option `WithSendEmail(true)` but not got any email, how can I fix it?

**Comment by bretterer** [comment]
Hello @rizkyekoputra. Thank you for your report here. The `sendEmail` query param is only for activation, not during the creation of a user.

Please see https://developer.okta.com/docs/reference/api/users/#activate-user for the details on this.

If you continue to have an issue, please feel free to re-open this issue.
