### ISSUE TITLE
URL's for methods need extra slash removed

### ISSUE THREAD

**Issue by bretterer** [okta/okta-sdk-golang#14]
The generator tool has `/api/v1/...` and the baseURL/orgURL in the config has a slash required at the end causing the final url to be built as `org.okta.com//api/v1/...`  

- [ ] During generation of models, remove the slash from the url.

- [ ] Add check during config to make sure the url ends in a `/`

**Comment by quantumew** [comment]
Gave this a stab while I was poking around the repository, let me know what you think #31.
