### ISSUE TITLE
No error summary when calling API with access token with insufficient scope

### ISSUE THREAD

**Issue by ikawalec** [okta/okta-sdk-golang#145]
# Steps to reproduce:

1. I've created a client credentials client using:
https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/create-publicprivate-keypair/
This client has only `okta.apps.manage` scope assigned.

2. Now I get an access token for this client (note that I'm also requesting additionall scope `okta.groups.read` here)
`curl -v -k "https://${yourOktaDomain}/oauth2/v1/token" -d "grant_type=client_credentials&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion=$JWT&scope=okta.apps.manage okta.groups.read"`

3. When I try to call API to get group by ID:
`curl -v -k -H "Authorization: Bearer $ACCESS_TOKEN" "https://${yourOktaDomain}/api/v1/groups/1234"`
I'm getting unauthorized response with no body and the following header
`www-authenticate: Bearer authorization_uri="http://***.okta.com/oauth2/v1/authorize", realm="http://dev-***.okta.com", scope="okta.groups.read", error="insufficient_scope", error_description="The access token provided does not contain the required scopes.", resource="/api/v1/groups/12345"`

4. When I'm doing the same using go client, I just get: `The API returned an error:`. There is no error summary of what actually went wrong.

# Expected result:
I want to have additional info in error why the call failed (this I guess can be taken from `www-authenticate` header)

**Comment by bretterer** [comment]
@ikawalec Thank you for your report here. We have added this to our updates that we will make in a future release.

Internal Ref: OKTA-331913
