### ISSUE TITLE
Add SamlGroupAttributeStatement type

### ISSUE THREAD

**Issue by ymylei** [okta/okta-sdk-golang#148]
We currently have [SamlAttributeStatement](https://pkg.go.dev/github.com/okta/okta-sdk-golang/v2@v2.0.0/okta?tab=doc#SamlAttributeStatement)

Which corresponds to [Attribute Statement object](https://developer.okta.com/docs/reference/api/apps/#attribute-statements-object)

We should add a SamlGroupAttributeStatement type which goes with [Group Attribute Statement object](https://developer.okta.com/docs/reference/api/apps/#group-attribute-statements-object)

**Comment by bretterer** [comment]
This has been addressed in v2.0.0.  Please update your dependency and this should fix your concern here.

If you have further issues, please re-open this issue and let us know what is going on.
