### ISSUE TITLE
Using wrong cache implementation

### ISSUE THREAD

**Issue by ymylei** [okta/okta-sdk-golang#149]
https://github.com/okta/okta-sdk-golang/blob/3737e52908b03014afa17c788211fe06f3fdef96/okta/config.go#L22

I'm pretty sure this should be using v2?

**Comment by bretterer** [comment]
This is on my list to get merged in today.  The PR is failing due to private env vars in travis

**Comment by ymylei** [comment]
> 
> 
> This is on my list to get merged in today. The PR is failing due to private env vars in travis

hey @bretterer mind cutting a patch release with this change in it? would like to use it on https://github.com/oktadeveloper/terraform-provider-okta/pull/153

**Comment by bretterer** [comment]
We are working on a few more changes @ymylei and will be releasing a new version soon.

**Comment by bretterer** [comment]
@ymylei This should be resolved in 2.1.0 now.

Please let us know if there are any other issues. Thank you!
