### ISSUE TITLE
Omitempty fields in OktaSignOnPolicyRuleSignonSessionActions struct break Okta API request validation rules

### ISSUE THREAD

**Issue by artemgavrilov** [okta/okta-sdk-golang#153]
According to [documentation](https://developer.okta.com/docs/reference/api/policy/#signon-session-object) Signon Session object fields are optional. However, for that request Okta API returns an error with summary `actions.signon.session.maxSessionLifetimeMinutes: The field cannot be left blank`.

```
curl -v -X POST \
-H "Accept: application/json"  \
-H "Content-Type: application/json"  \
-H "Authorization: SSWS ${api_token}"  \
-d '{
   "type":"SIGN_ON",
   "actions":{
      "signon":{
         "access":"ALLOW",
         "session":{
            "maxSessionIdleMinutes":10080
         }
      }
   },
   "conditions":{
      "authContext":{
         "authType":"ANY"
      },
      "network":{
         "connection":"ANYWHERE"
      }
   },
   "name":"Test"
}' "https://${yourOktaDomain}/api/v1/policies/${policyId}/rules"
```

With curl I can just add required fiedls with default values `"session":{"maxSessionIdleMinutes":10080, "maxSessionLifetimeMinutes":0, "usePersistentCookie":false}`, but in [SDK this fields are marked with omitempty](https://github.com/okta/okta-sdk-golang/blob/0b49dc66c11a320208262078bb928d1e5298a98a/okta/oktaSignOnPolicyRuleSignonSessionActions.go#L24-L26) so it's not possible to pass zero values. 

Right now I copy-pasted `okta.OktaSignOnPolicyRuleSignonSessionActions` structure to my code, removed `omitempty` and invoke required endpoint with `requestExecutor`. 

It will be nice if that problem will be fixed, on the Okta API request validation side or on the documentation/SDK side.

**Comment by bretterer** [comment]
Thank you for the report here. I will bring this up with the team to take a look at.

Internal Ref: OKTA-331914

**Comment by bogdanprodan-okta** [comment]
This issue was fixed in v.2.2.2
