### ISSUE TITLE
Duplicate policy rule function

### ISSUE THREAD

**Issue by ymylei** [okta/okta-sdk-golang#154]
https://github.com/okta/okta-sdk-golang/blob/3737e52908b03014afa17c788211fe06f3fdef96/okta/policy.go#L256

and

https://github.com/okta/okta-sdk-golang/blob/3737e52908b03014afa17c788211fe06f3fdef96/okta/policyRule.go#L40

I suppose more in general, there is update and delete in the "PolicyRuleResource", but full CRUD in the "PolicyResource" for rules. I think those should be consolidated.

**Comment by bretterer** [comment]
Thank you for bringing this to our attention @ymylei.  I will talk with the team about this, but we do treat each model as a standalone model. I believe in documentation, we talk about Policy and it has this updateRule method defined, but we also talk about PolicyRule and it too defines the UpdatePolicy.  
I will talk this over with the team, but for now, you can pick whichever area you are in.

**Comment by monde** [comment]
@ymylei I'm triaging our long lived issues ... let me know how important this is for you. Thanks
