### ISSUE TITLE
Error While building the sdk locally

### ISSUE THREAD

**Issue by nikhilpulluri** [okta/okta-sdk-golang#155]
I am getting below error when trying to build the sdk locally, can someone help me on the issue

Generating SDK Files...
cd openapi && yarn generator
yarn run v1.22.4
$ okta-sdk-generator -t generator -o ../ 
/bin/sh: okta-sdk-generator: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make[1]: *** [generate-files] Error 127
make: *** [build] Error 2

**Comment by bretterer** [comment]
@nikhilpulluri Hello!  Thanks for reaching out.  The `make build` command provided is for use during development of the SDK itself. It requires you to have the `okta-sdk-generator` command that comes from `@okta/openapi` javascript package. This is publically available on npm.js.  If you `cd openapi` from the root, and run `yarn install` you should be able to run the `make build` command. 

However, there should not be a need to do this as this will just generate the SDK again as it is from Github. if you are trying to build a binary of the sdk itself, you will need to run Go's internal builder.

Hope this helps
