### ISSUE TITLE
Missing link of Okta+Golang doc

### ISSUE THREAD

**Issue by haishengwu-okta** [okta/okta-sdk-golang#156]
In readme

> You can learn more on the Okta + Golang page in our documentation.

but the link is 404: https://github.com/okta/okta-sdk-golang/blob/master/lang-landing

**Comment by bretterer** [comment]
Thanks @haishengwu-okta.   We will get that fixed

**Comment by haishengwu-okta** [comment]
Thank you your quick feedback @bretterer !!
