### ISSUE TITLE
filter function not working on ListGroupUsers

### ISSUE THREAD

**Issue by felixn-unity** [okta/okta-sdk-golang#169]
Hi

filter function seems to be ignored when using ListGroupUsers :

var filter = query.NewQueryParams(query.WithFilter("status eq \"ACTIVE\""))
users, resp, err := client.Group.ListGroupUsers(ctx, "my user group", filter)

Thanks
Felix

**Comment by bretterer** [comment]
Hello!  Could you please expand on this a little bit.  What are you expecting to get, what are you getting instead?  Can you provide a little more detail here.

From the initial look at this, It seems your call is using the string `my user group` for the `groupId` param of the `ListGroupUsers` call.  This should instead be the id provided as part of the group, not the name of the group.

I would love to see the actual response from your api call for this

**Comment by felixn-unity** [comment]
Hi

Sure, "my user group" is the group ID, but ListGroupUsers returns all users with any status.

So to fix it, I am checking when I am looping through the results - which was not expected to do that :

        var filter = query.NewQueryParams(query.WithFilter("status eq "ACTIVE""))
	users, resp, err := client.Group.ListGroupUsers(ctx, 0xXXXXXXXX, filter)
	if err == nil {
		for i := 0; i < len(users); i++ {
			if users[i].Status == "ACTIVE" {
                         //
                         //
			}
		}
       }

Thanks
Felix

**Comment by bretterer** [comment]
Thanks for this information.  Let me work on reproducing this and ill be getting back to you shortly

**Comment by felixn-unity** [comment]
Thanks a lot, do let me know if I should try/do anything

Felix

**Comment by bretterer** [comment]
So, that is what I expected.  The method `listGroupUsers` references the endpoint that is documented at https://developer.okta.com/docs/reference/api/groups/#list-group-members.  This specific endpoint only accepts `limit` and `after` as query parameters. We do not allow filtering on this specific api call.


Parameter | Description | ParamType | DataType | Required | Default
-- | -- | -- | -- | -- | --
after | Specifies the pagination cursor for the next page of users | Query | String | FALSE |  
limit | Specifies the number of user results in a page | Query | Number | FALSE | 1000


As the api and SDK is working as intended, I can suggest that after you get your users in the group, you can then iterate through each user and check yourself for the active users.

**Comment by felixn-unity** [comment]
Ok I see, thanks and sorry for the fuzz :)

Felix

**Comment by bretterer** [comment]
No need to be sorry.  Just as an FYI, most of our methods in the SDK correlate to a name in our documentation.  How you can decerifer where these are documented at, you can use the client name of the call.

ie. any `client.Group` call will be documented and found in the Groups resource of our documentation page found at https://developer.okta.com/docs/reference/ .  Once you get into groups, what I will typically do is find the url of the call you are using. So in your case, you are using `ListGroupUsers` which has a url of `/api/v1/groups/%v/users`. This will translate to `api/v1/groups/${groupId}/users` in our documentation, so you can just do a find in page for that url.

Hope this helps.  Let us know if we can help any further
