### ISSUE TITLE
openIdConnectApplicationSettingsClient does not contain jwks field

### ISSUE THREAD

**Issue by pawelaugustyn** [okta/okta-sdk-golang#176]
Provided implementation of [openIdConnectApplicationSettingsClient](https://github.com/okta/okta-sdk-golang/blob/master/okta/openIdConnectApplicationSettingsClient.go) structure does not include `jwks` field. This difference causes that available structure does not reflect JSON structure shown in Okta API reference ([Apps > Application operations > Add aplication > private_key_jwt set as token_endpoint_auth_method](https://developer.okta.com/docs/reference/api/apps/#request-example-11)).
This basically blocks creating applications with Private Key JWT set as an auth method for token endpoint without defining custom structures that implement `App` interface

**Comment by bretterer** [comment]
@pawelaugustyn thank you for the report here.  We did just update some information in this structure, but seems we missed `jwks` field.

As a workaround for now, you could create a new custom structure that includes this field and then use our system to [call external api endpoints](https://github.com/okta/okta-sdk-golang#call-other-api-endpoints).  I know this is not ideal at the moment, but we will adjust our spec to get this updated.

**Comment by bretterer** [comment]
Internal Ref: OKTA-341692

**Comment by bretterer** [comment]
@pawelaugustyn we are currently working on this issue and will be releasing a new version of the SDK soon which will include a fix here.

**Comment by bretterer** [comment]
@pawelaugustyn thank you for the raising this issue.  Sorry I missed coming back here to update that it has been included in a release.

If there is anything else that I can help with, please let me know!

**Comment by pawelaugustyn** [comment]
We've already started using that. Thanks for providing the fix so quickly!
