### ISSUE TITLE
Group profile parameters

### ISSUE THREAD

**Issue by denys-volkov-sp** [okta/okta-sdk-golang#181]
Hello guys, can you extend groupProfile with other parameters? https://github.com/okta/okta-sdk-golang/blob/master/okta/groupProfile.go#L19-L24 which mention in doc here https://developer.okta.com/docs/reference/api/groups

Example:
```
type GroupProfile struct {
	Name                       string `json:"name,omitempty"`
	Description                string `json:"description,omitempty"`
	WindowsDomainQualifiedName string `json:"windowsDomainQualifiedName,omitempty"`
	GroupType                  string `json:"groupType,omitempty"`
	GroupScope                 string `json:"groupScope,omitempty"`
	SamAccountName             string `json:"samAccountName,omitempty"`
	ObjectSid                  string `json:"objectSid,omitempty"`
	ExternalId                 string `json:"externalId,omitempty"`
	DN                         string `json:"dn,omitempty"`
}
```

**Comment by bretterer** [comment]
Thanks for the report @denys-volkov-sp.  I will be looking into this concern.  It seems that these properties may be available through an Early Access program, but not normally available. I am looking into it a little more though.

**Comment by bretterer** [comment]
Following up with you on this @denys-volkov-sp.  As we are still looking into this one, I wanted to suggest a path to unblock you. In our SDK, we allow you to make calls to API endpoints that are not fully covered. The information for how to do this can be found in [our readme](https://github.com/okta/okta-sdk-golang#call-other-api-endpoints)

If this path does not unblock you for now, please let us know and we will try to come up with another solution while we work on details about the missing properties here.

**Comment by denys-volkov-sp** [comment]
Hello @bretterer, thank you 👍 my current code has already based on this solution, which you mentioned above. I see one problem with it, I extend SDK with own method and with my URL and if SDK change the url then my code will work wrong. What do you think about it?

**Comment by bretterer** [comment]
What URL are you worried about changing here?  The URL's are defined by the Okta API, so this should not be an issue

**Comment by monde** [comment]
@denys-volkov-sp I'm triaging our long lived issues; are you still looking for a new feature here?
