### ISSUE TITLE
Missing support Schemas API

### ISSUE THREAD

**Issue by noinarisak** [okta/okta-sdk-golang#188]
Looking over the api doc references it does not seem the SDK v2 supports the [Schema API](https://developer.okta.com/docs/reference/api/schemas/) endpoint at this time.

**Comment by bretterer** [comment]
Hey @noinarisak. It seems that we currently support the `linkedObjects` schema, but that is it.

The best I can tell you to do now is use the [Calling other endpoints](https://github.com/okta/okta-sdk-golang#call-other-api-endpoints) option that we provide in the SDK.  I will add this to our backlog to take a look at adding in a future release of the spec.

**Comment by bretterer** [comment]
Internal Ref: OKTA-347834

**Comment by monde** [comment]
Hi @noinarisak we released schema API support in 6d16b62b9ad56de18e0501d16e8d59c3c6b43eec Sdk v2 (#137) release tagged #v2.0.0 . I'm going to close out this issue.

**Comment by monde** [comment]
@noinarisak Please bring the issue back up if v2.0.0 doesn't resolve this issue for you.
