### ISSUE TITLE
How to get list of groups filtered by app parameters (appID, appName, appLabel)?

### ISSUE THREAD

**Issue by denys-volkov-sp** [okta/okta-sdk-golang#189]
Hello guys, exists way to filter group list by app parameters (appID, appName, appLabel)? Currently I'm working with group-role mapping functionality, in application exists parameter as **App Filter**, so by documentation we must filter groups based on **App Filter**, but I didn't find solution where it can be done via Okta API. I'm going through all groups in the list and match them on group-role mapping, and it's so slow.

For example:
- If I have groups (APP_GROUP) about ~300k, but I need just process 20 groups from appID 0oaovrIn4R6AFNZeW0g3, it will be faster if I just filter groups by appID and process only 20 instead ~300k

**Comment by bogdanprodan-okta** [comment]
I think this is what you are looking for https://developer.okta.com/docs/reference/api/groups/#search-examples
It's still an `early access` feature, so it won't work for all organizations.

**Comment by denys-volkov-sp** [comment]
bloodsicker@bogdanprodan-okta thank you for the answer. Current feature solve search by appID, but not for search by appLabel, and appName. 

I found parameter **expand** for group and it return all data I need for filter, but seems Okta API not support filtering by parameter **_embedded**.
```
"_embedded": {
            "app": {
                "id": "0oau455t52QMtU3qT0h8",
                "name": "active_directory",
                "label": "oktaad.com",
                "signOnMode": null,
                "key": "app"
            }
}
```

So, will Okta add new API for support filtering for groups list by app parameters? It will simplify searching groups by app parameters
