### ISSUE TITLE
ListApplications with paging fails with marshaling error

### ISSUE THREAD

**Issue by alsmola** [okta/okta-sdk-golang#191]
I found a similar bug to https://github.com/okta/okta-sdk-golang/issues/87 and https://github.com/okta/okta-sdk-golang/issues/41, but for paging through `ListApplications`.

When running this code:

```
apps, resp, err := client.Application.ListApplications(ctx, nil)
for resp.HasNextPage() {
    var nextApps []okta.App
    resp, err = resp.Next(ctx, &nextApps)
    apps = append(apps, nextApps...)
}	
```

At the line where I call `Next()`, I get this error:

```
cannot unmarshal object into Go value of type okta.App
```

I'm guessing that whatever was done to address the marshaling error for `App` interfaces in the linked issues doesn't work for the `Next()` functionality.

**Comment by bretterer** [comment]
@alsmola Thank you for reporting this.  It does seem like this may have been a regression from our fixes to `App` marshaling.  One thing you could try is to set `var nextApps []okta.Application` instead of `App`.  Not 100% this would work as a workaround for you though.

I am going to create a report with our team to take a look at this and see what we can do to address this.

Please let us know if swapping to `Application` unblocks you.

**Comment by bretterer** [comment]
Internal Ref: OKTA-354506

**Comment by alsmola** [comment]
Changing to `[]*okta.Application` prevents the error, but now I'm running into another one calling`Next()`:

`Not found: Resource not found: <value omitted> (AppLink)`

Perhaps I should be limiting my query in some way?

**Comment by bretterer** [comment]
Odd, I would not have expected that error.  It does seem like there is something up with it in general that we will take a look at.

As you mention, you could use some params to limit your query.  depending on what you are trying to do with your listed applications, you could use any one of the following queries from our docs: https://developer.okta.com/docs/reference/api/apps/#request-parameters-3

We will make sure we look at this bug and let you know here when we have a resolution

**Comment by bogdanprodan-okta** [comment]
You can try doing something like this:
```go
ctx, cancel := context.WithCancel(ctxFromOkta)
apps, resp, err := client.Application.ListApplications(ctx, &query.Params{Limit:1})
for resp.HasNextPage() {
	var nextApps []okta.Application
	resp, err = resp.Next(ctx, &nextApps)
	applications := make([]okta.App, len(nextApps))
	for i := range nextApps {
		applications[i] = &nextApps[i]
	}
	apps = append(apps, applications...)
}
```
I know, it looks not very nice, but at least it works.
