### ISSUE TITLE
Option WithHttpClient(httpClient http.Client) requires argument passed by value instead of pointer

### ISSUE THREAD

**Issue by programmer04** [okta/okta-sdk-golang#193]
Hello!

As described in the title, on the other hand in [Readme.md](https://github.com/okta/okta-sdk-golang/blob/0f3120d96a68cec377e761e20adc42e9125353b1/README.md#extending-the-client) passing by a pointer is described, which is desired but cannot be performed in the current SDK, please see [WithHttpClient(httpClient http.Client)](https://github.com/okta/okta-sdk-golang/blob/0f3120d96a68cec377e761e20adc42e9125353b1/okta/config.go#L138)

Official Go documentation says [that using the same instance is desired](https://golang.org/pkg/net/http/#Client) and passing as a pointer is a common pattern for instance in [google-api-go-client](https://github.com/googleapis/google-api-go-client/blob/f7ce5abca6e37cc937e5fe7992ba06892fb0d7fe/option/option.go#L108).

**Comment by bretterer** [comment]
@programmer04 Thank you for pointing out the conflicting information in our readme and code. We are going to add this into our workflow to take a look at fixing. 

Is this currently blocking you with your work, or are you able to pass by value to continue working while we work to get a fix in place?

**Comment by programmer04** [comment]
@bretterer thanks for the very fast response. It's not a blocking thing, just I can't inject my custom `http.Cliennt` in an optimal way. The fix shouldn't be hard to but it breaks the current API of SDK

**Comment by bretterer** [comment]
@programmer04 No problem.  That is the issue with this update. Since we're not ready to release a new major version of the SDK right now, we need to find a way to not break backwards compatibility.

Keep following this ticket for a resolution and please let us know if you run into a blocker because of this.

**Comment by bretterer** [comment]
Internal Ref: OKTA-360179
