### ISSUE TITLE
Type PolicyRule struct is missing properties

### ISSUE THREAD

**Issue by noinarisak** [okta/okta-sdk-golang#197]
Can we match fields identified in our [docs](https://developer.okta.com/docs/reference/api/policy/#rules-object
) or at least have the require `name` field?

Referring to code block:
https://github.com/okta/okta-sdk-golang/blob/master/okta/policyRule.go#L29-L37

At the moment, I not sure how to get the `name` field after getting array of `okta.PolicyRule`.

ie.
```golang
	output, resp, err := client.Policy.ListPolicyRules(ctx, policyID)
	if err != nil {
		return nil, e
	}

	for resp.HasNextPage() {
		var nextPolicySet []*okta.PolicyRule
		resp, err = resp.Next(ctx, &nextPolicySet)
		output = append(output, nextPolicySet...)
	}

       return output
        ...
```

**Comment by bretterer** [comment]
@noinarisak, the Name field lives on the specific PolicyRule types, such as https://github.com/okta/okta-sdk-golang/blob/master/okta/passwordPolicyRule.go

Is there a reason you need the name on the generic PolicyRule, vs the specific PolicyRule?

**Comment by noinarisak** [comment]
Thanks, @bretterer it was not apparent to me that I have to do type conversion base on `PolicyRule.Type` for all three types: `password`, `oktaSignOn`, `MFA enroll`. Plus it does look like `MFA_ENROLL` has been implemented maybe due to Beta status?

**Comment by noinarisak** [comment]
Hey, @bretterer and/or @bogdanprodan-okta . I decided to go with `github.com/oktadeveloper/terraform-provider-okta/sdk` implementation to handle converting a `PolicyRule` to a particular type (ie `PasswordType`).  I'm not sure how to go about doing a type conversion without an interface. I prefer going with just a single SDK but if my approach is to use `ListPolicyRules(ctx, policyID)` method but no way to type convert a list of the policy-rules objects to get `PasswordType` and attributes, for example, I'm at a lost. What is the expected approach?

The `github.com/oktadeveloper/terraform-provider-okta/sdk` is doing it the following way

https://github.com/oktadeveloper/terraform-provider-okta/blob/029386db8a55f5f56c9817ed886003c561db10e2/sdk/policy_rule.go#L11-L59

Thanks for the help!

**Comment by monde** [comment]
Internal Ref: [OKTA-409809](https://oktainc.atlassian.net/browse/OKTA-409809)

**Comment by noinarisak** [comment]
Thanks @monde !

**Comment by duytiennguyen-okta** [comment]
This should be resolved in v3. We are no longer supporting v2
