### ISSUE TITLE
Requests to Okta are not retried on connection problems errors

### ISSUE THREAD

**Issue by adw1n** [okta/okta-sdk-golang#198]
Any connection problems are considered permanent and requests to Okta don't get retried by `okta-golang-sdk`. In my service's logs I see requests done by okta-golang-sdk fail from time to time with error:
```
Post "https://{redacted my custom org domain name}/api/v1/apps": EOF
```
and these requests don't get retried.

This is the problematic code block:
https://github.com/okta/okta-sdk-golang/blob/bb2e8ecf6ad832bfdfb8216fb3a653294e6274b5/okta/requestExecutor.go#L298-L301

I think the author's @bogdanprodan-okta  intention was to respect the configured request timeouts but as a side effect requests that fail immediately (<30ms) because of a broken connection aren't retried.

**Comment by bogdanprodan-okta** [comment]
Hi @adw1n! Thanks for submitting this issue! I'll add some `if` clause to check for `EOF` errors.

**Comment by adw1n** [comment]
@bogdanprodan-okta would you be willing to release v2.2.3 with this fix soon?
