### ISSUE TITLE
Option okta.WithPrivateKey panics on long private key strings

### ISSUE THREAD

**Issue by adw1n** [okta/okta-sdk-golang#206]
`okta.WithPrivateKey` on MacOS panics when passing a string that contains a legitimate private key.

`okta.WithPrivateKey` calls `fileExists` at the beginning of the function:
https://github.com/okta/okta-sdk-golang/blob/4a984fd6db90e2734920c3db9e26a693a3117b9c/okta/config.go#L189
This piece of code https://github.com/okta/okta-sdk-golang/blob/4a984fd6db90e2734920c3db9e26a693a3117b9c/okta/config.go#L201-L207 ignores `file name too long` errors. Only `os.IsNotExist(err)` error is checked and on any other error https://github.com/okta/okta-sdk-golang/blob/4a984fd6db90e2734920c3db9e26a693a3117b9c/okta/config.go#L206 is reached and `info` variable is `nil`. Regardless of if you want to officially support MacOS or not the https://github.com/okta/okta-sdk-golang/blob/4a984fd6db90e2734920c3db9e26a693a3117b9c/okta/config.go#L201-L207
implementation should be changed.

Steps to reproduce on linux:
```
export OKTA_CLIENT_PRIVATEKEY=$(python3 -c 'print("a\n" * 1000)')
go run withprivatekeypanic.go
```

```
// withprivatekeypanic.go
package main

import (
	"os"

	"github.com/okta/okta-sdk-golang/v2/okta"
)

func main() {
	oktaPrivateKey := os.Getenv("OKTA_CLIENT_PRIVATEKEY")
	okta.WithPrivateKey(oktaPrivateKey)(nil)
}

```

error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=redacted addr=redacted pc=redacted]

goroutine 1 [running]:
github.com/okta/okta-sdk-golang/v2/okta.fileExists(redacted, redacted, redacted)
```

Panic happens on https://github.com/okta/okta-sdk-golang/blob/4a984fd6db90e2734920c3db9e26a693a3117b9c/okta/config.go#L206

Please change the implementation to at the very least check for `file name too long` errors.

**Comment by bogdanprodan-okta** [comment]
Hi @adw1n! Thanks for submitting this issue! I'll create a corresponding PR.

**Comment by adw1n** [comment]
Problem described in this issue got fixed in https://github.com/okta/okta-sdk-golang/pull/207 although the `fileExists`  error handling could use further improvements. My code that panicked on MacOS previously now works after okta-sdk-golang library update.

@bogdanprodan-okta please link to issues in your PRs https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
