### ISSUE TITLE
`make build` produces invalid output

### ISSUE THREAD

**Issue by aborrello** [okta/okta-sdk-golang#220]
👋 I've ran into some issues while trying to build the SDK as per the README instructions.

Here is the error I receive when running `make build` from the repository root:

```
$ make build
... (skipping for brevity)
Running Goimports on generated files...
okta/userSchema.go:26:2: illegal character +0024 '$'
okta/userSchema.go:43:2: expected declaration, found 'if'
okta/userSchema.go:50:2: expected declaration, found resp
okta/userSchema.go:71:2: expected declaration, found resp
okta/userSchema.go:92:2: expected declaration, found resp
okta/userSchema.go:113:2: expected declaration, found resp
make[1]: *** [generate-files] Error 2
make: *** [build] Error 2
```

The following Go errors exist in the `userSchema*` packages:
```
# github.com/okta/okta-sdk-golang/v2/okta
./okta.go:52:23: undefined: UserSchemaResource
./userSchema.go:26:2: invalid character U+0024 '$'
./userSchema.go:39:10: undefined: UserSchemaResource
./userSchema.go:39:59: undefined: context
./userSchema.go:56:10: undefined: UserSchemaResource
./userSchema.go:56:63: undefined: context
./userSchema.go:73:10: undefined: UserSchemaResource
./userSchema.go:73:48: undefined: context
./userSchema.go:90:10: undefined: UserSchemaResource
./userSchema.go:90:52: undefined: context
./userSchema.go:90:52: too many errors
```

Looking in that file, it looks like a field `$schema` has been added to the `UserSchema` struct and the `type UserSchemaResource resource` has been omitted...

```go
// Code generated by okta openapi generator. DO NOT EDIT.

package okta

import (
)


type UserSchema struct {
	$schema string `json:"$schema,omitempty"`
	Links interface{} `json:"_links,omitempty"`
	Created string `json:"created,omitempty"`
	...
```

Any ideas what could be causing this / how to resolve this problem?

**Comment by bryanapellanes-okta** [comment]
@aborrello, 
Thanks for reaching out!  Our Go developers will investigate and comment here when there is additional information to share.

Thanks for using Okta!

**Comment by bogdanprodan-okta** [comment]
Hi, @aborrello! The problem here is with the SDK generator as it has not yet been fixed yet to support the latest version of Okta's `open-api-spec`. Please just use the SDK "as-is" without regenerating the files. If you have any other issues, feel free to ask.

**Comment by halmai** [comment]
Hi, I cannot create my Pull Request until the build process gets fixed. Could you fix it soon, please?

**Comment by monde** [comment]
The 🐉 is on the case.

**Comment by monde** [comment]
I have a branch to fix this issue ( https://github.com/okta/okta-sdk-golang/tree/fix-make-build-issue-220 ) but we won't be able to release it until we publish the next version of okta-sdk-golang that is based on the public facing openapi spec in https://github.com/okta/okta-management-openapi-spec

**Comment by monde** [comment]
@aborrello @halmai the master branch has our latest release of 2.5.0 of the okta-sdk-golang. I fix the issues you all ran into. I'll close this issue, let me know if you are still blocked.
