### ISSUE TITLE
support Domains API

### ISSUE THREAD

**Issue by jeffg-hpe** [okta/okta-sdk-golang#229]
Requesting support for the new [Domains API](https://developer.okta.com/docs/reference/api/domains/). It is in Early Access.

Needed for https://github.com/okta/terraform-provider-okta/issues/410

**Comment by bryanapellanes-okta** [comment]
@jeffg-hpe,
Thanks for reaching out! I'll bring this to the attention of our golang developers and someone will follow up.

Thanks for using Okta!

**Comment by bryanapellanes-okta** [comment]
Internal Ref: OKTA-395688

**Comment by bretterer** [comment]
Hi @jeffg-hpe,

Thanks for the request.  Good news! This is in the works!  I am not sure of the release date yet, but know that we are actively working on it.

**Comment by monde** [comment]
`/api/v1/domains` is supported in the 2.5.0 release of okta-sdk-golang
