### ISSUE TITLE
Inaccurate README.md

### ISSUE THREAD

**Issue by Sanil2108** [okta/okta-sdk-golang#231]
As per the README, the way to create a user is using the function `CreateUser` and passing an Okta User struct and query params
https://github.com/okta/okta-sdk-golang/blob/master/README.md#create-a-user. However, the way it is defined is different, we need to pass a Context, CreateUserRequest and query params - https://github.com/okta/okta-sdk-golang/blob/master/okta/user.go#L49

**Comment by monde** [comment]
@Sanil2108 can you get me a PR to improve our documentation? Thanks for catching this misleading information.

**Comment by monde** [comment]
@Sanil2108 I'll be doing a 2.5.1 release of the sdk this sprint and update the README with the correct CreateUser example as part of the release.

**Comment by monde** [comment]
README updated with proper CreateUser documentation, closing issue, thank you @Sanil2108
