### ISSUE TITLE
Support Org APIs

### ISSUE THREAD

**Issue by gavinbunney** [okta/okta-sdk-golang#234]
Requesting support for the [Org APIs](https://developer.okta.com/docs/reference/api/org/) to allow management of org-related settings via Terraform. It is in Early Access.

**Comment by aarongranick-okta** [comment]
@gavinbunney Thank you for the request. An Okta engineer will investigate and respond with more detail. 
Internal ref: OKTA-409128

**Comment by monde** [comment]
@bogdanprodan-okta shouldn't this issue be reflected on https://github.com/okta/okta-management-openapi-spec ?

**Comment by bogdanprodan-okta** [comment]
@monde yes, we are missing that from the spec

**Comment by bogdanprodan-okta** [comment]
@gavinbunney we are currently working on adding this functionality to the official specs so it will available in Golang SDK soon. Cheers!

**Comment by duytiennguyen-okta** [comment]
This is now supported in TF https://registry.terraform.io/providers/okta/okta/latest/docs/resources/org_configuration
