### ISSUE TITLE
HasNextPage method does not respect query object

### ISSUE THREAD

**Issue by noinarisak** [okta/okta-sdk-golang#242]
Hi team, The following code does not appear to acknowledge the `query` params when I'm trying to get all the "SAML2" type IDPs in my Okta org. In the below code my use case I only have one 1 saml idp, but when we hit `resp.HasNextPage()` actually comes back `true` which then proceeds to pull my other IDPs, my case `OIDC` idp. With `Delve` I notice that `after=` is of course being implemented since that is apart of pagination implementation but the `type=` was not apart of the query string. I might be missing an implementation detail, wouldn't be the first. 😅  So some guides there would be great!

```golang
func getIDPSaml(ctx context.Context, client *okta.Client) ([]*okta.IdentityProvider, error) {
	qp := query.NewQueryParams(query.WithType("SAML2"))
	output, resp, err := client.IdentityProvider.ListIdentityProviders(ctx, qp)
	if err != nil {
		return nil, err
	}

	for resp.HasNextPage() {
		var nextIDPSamlSet []*okta.IdentityProvider
		resp, _ = resp.Next(ctx, &nextIDPSamlSet)
		output = append(output, nextIDPSamlSet...)
	}

	return output, nil
}

```

Let me know if you need the complete implementation and I'm still on v2.3.1. I did a quick/scan between 2.3.1 vs 2.5.0 and didn't see if this was resolved between versions.

Thanks again!

**Comment by arvindkrishnakumar-okta** [comment]
@noinarisak Thanks for posting!

Will have our team take a look at this.

**Comment by noinarisak** [comment]
@arvindkrishnakumar-okta Just wondering if there has been any progress. After looking over https://github.com/okta/okta-sdk-golang/blob/c954cb6883a249f4bbe73b2f361de95d2bdbba22/okta/requestExecutor.go#L406-L432, I wonder if it is just how our `idp` endpoint is not a filtered dataset when the pagination is being implemented.

**Comment by noinarisak** [comment]
Thanks @bogdanprodan-okta ! I implemented the following per your recommendation 

```golang
func getIdpSAML(ctx context.Context, client *okta.Client) ([]*okta.IdentityProvider, error) {
	qp := &query.Params{Type: "SAML2", Limit: 1}
	output, resp, err := client.IdentityProvider.ListIdentityProviders(ctx, qp)
	if err != nil {
		return nil, err
	}

	for resp.HasNextPage() {
		var nextIdpSAMLSet []*okta.IdentityProvider
		resp, err = resp.Next(ctx, &nextIdpSAMLSet)
		if err != nil {
			return nil, err
		}
		output = append(output, nextIdpSAMLSet...)
	}

	return output, nil
}
```

So I have two SAML2 and one OIDC in my tenant. When I'm debugging with delve, it still picks up the third OIDC idp record. Only difference is my `qp` object is inside my function. Not sure if I'm missing any details.

**Comment by noinarisak** [comment]
Thanks, @bogdanprodan-okta, for PR #253!
