### ISSUE TITLE
Support additional group profile properties

### ISSUE THREAD

**Issue by ymylei** [okta/okta-sdk-golang#268]
Per https://developer.okta.com/docs/reference/api/groups/#custom-profile-properties:

The `OKTA_GROUP` class groups can now have extended profile attributes completely up to the user requirements. Are we able to update the group interfaces to support an arbitrary map of custom group profile attributes, while keeping the "default" attributes and interface relatively unchanged?

**Comment by monde** [comment]
@ymylei I will take a look and give you an answer later today.

**Comment by ymylei** [comment]
This seems like the generator should work OK:

The `GroupProfile` is defined at: https://github.com/okta/okta-management-openapi-spec/blob/bf41db85968b6a189cb9f56b2c5ceed194fd8356/resources/spec.yaml#L10006

The `UserProfile` is defined at: https://github.com/okta/okta-management-openapi-spec/blob/bf41db85968b6a189cb9f56b2c5ceed194fd8356/resources/spec.yaml#L15113

I don't see anything where the inclusion of something in the base schema is causing issue, but looking at this SDK and the Python SDK I don't see the options for user defined profile attributes to be passed in the objects

**Comment by ymylei** [comment]
Actually I think I figured out the why here, it looks like there is an override in place for the `UserProfile` model: https://github.com/okta/okta-sdk-golang/blob/8b91031c61c1cbd215ecfddc42a53c9cfdfe910c/openapi/generator/templates/model.go.hbs#L5

I think this will have to be replicated for the `GroupProfile` model.

**Comment by ymylei** [comment]
Looks like the python generator is also using overrides for the `UserProfile` model: https://github.com/okta/okta-sdk-python/blob/master/openapi/templates/model.py.hbs

**Comment by monde** [comment]
> Actually I think I figured out the why here, it looks like there is an override in place for the `UserProfile` model:
> 
> https://github.com/okta/okta-sdk-golang/blob/8b91031c61c1cbd215ecfddc42a53c9cfdfe910c/openapi/generator/templates/model.go.hbs#L5
> 
> I think this will have to be replicated for the `GroupProfile` model.

Apologies (again) for the late reply @ymylei .

Check this branch out, is this what you'd like to see on the group profile?:
https://github.com/okta/okta-sdk-golang/compare/group_profile_interface

**Comment by rlewis-grax** [comment]
Hi All. Sorry to jump in out of the blue, but I have a project blocked by this exact requirement. The proposal above by monde is exactly the behavior I would expect (both for consistency and extensibility) for group attributes.

**Comment by monde** [comment]
@ymylei @rlewis-grax , in speaking with @bogdanprodan-okta , he points out that at this point in okta-sdk-golang's `2.*.*` history, randomly changing the type of `GroupProfile` from a struct to a map string interface is a backwards compatibility breaking change. Developer Experience at Okta places a premium on maintaining backwards compatibility.

Side note: There will be a `3.0.0` release of okta-sdk-golang coming in the next couple of months and we'd have no constraint starting wotj group profile defined as `type GroupProfile map[string]interface{}`

So, for the next release of okta-sdk-golang (`2.9.2`) @bogdanprodan-okta suggested we embed the map string interface capability on the current `GroupProfile` struct. The implementation would be as follows:

```go
type GroupProfileMap map[string]interface{}

type GroupProfile struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	GroupProfileMap
}
```

He and I would enhance the JSON marshaling in the API code to handle that. After, developers would be able to implement code like this example:

```go
    gp := GroupProfile{
		Name:        "Foo",
		Description: "Bar",
		GroupProfileMap: GroupProfileMap{
			"name_2":         "heelo",
			"custom_field": "world",
		},
	}

	b, err := json.Marshal(&gp)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(b))

	/* Output:
	{"custom_field":"world","description":"Bar","name":"Foo","name_2":"heelo"}
	*/

	var gp2 GroupProfile

	err = json.Unmarshal(b, &gp2)
	if err != nil {
		panic(err)
	}
	fmt.Println()
	fmt.Println(fmt.Sprintf("%+v", gp2))
	
    /* Output:
	{Name:Foo Description:Bar GroupProfileMap:map[custom_field:world name_2:heelo]}
	*/
```

@ymylei @rlewis-grax let me know how this sounds to you all. I need to release a `2.9.2` version of okta-sdk-golang in the next couple of days. (thank you @bogdanprodan-okta !)

**Comment by rlewis-grax** [comment]
This satisfies my use case. Thanks for the speedy response y'all.

**Comment by monde** [comment]
I'll have @bogdanprodan-okta look at my PR #272 with these changes when he gets in.

**Comment by monde** [comment]
Just released [v2.9.2](https://github.com/okta/okta-sdk-golang/releases/tag/v2.9.2) with these accommodating types. Thanks for the input @ymylei @rlewis-grax 

```go
type GroupProfileMap map[string]interface{}

type GroupProfile struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	GroupProfileMap
}
```

**Comment by ymylei** [comment]
@monde Cheers! Yea I think this makes sense for now, personally I think y'all may want to consider moving to a standard/custom struct where you have:
```
type GroupProfile struct {
    StandardProfile struct {
         Name string
         Description string
     }
    CustomProfile map[string]interface{}
}

Or something "roughly" like this for the GroupProfile and UserProfile. Purely my own opinion though, I think it would make the most "sense" as a consumer of the profile interfaces where you do have the standard stuff as well as the DIY fields.

**Comment by monde** [comment]
> @monde Cheers! Yea I think this makes sense for now, personally I think y'all may want to consider moving to a standard/custom struct where you have:
> 
> ```
> type GroupProfile struct {
>     StandardProfile struct {
>          Name string
>          Description string
>      }
>     CustomProfile map[string]interface{}
> }
> ```
> 
> Or something "roughly" like this for the GroupProfile and UserProfile. Purely my own opinion though, I think it would make the most "sense" as a consumer of the profile interfaces where you do have the standard stuff as well as the DIY fields.

@ymylei I'll keep that in mind when we roll out v3.0.0, thanks for the feedback.
