### ISSUE TITLE
I am not able to use ListUsers in user.go

### ISSUE THREAD

**Issue by gbhatiaRV** [okta/okta-sdk-golang#270]
I am not able to use ListUsers function using search queryParam.
 My queryString is correct here as I am able to get results when I am hitting the API with postman.

url I am passing is - /api/v1/users?search=profile.proxyAddresses+eq+"email Address"
Below code is returning just this message "{"level":"info","msg":"The API returned an error: "}"

req, err := m.client.requestExecutor.NewRequest("GET", url, nil)
	if err != nil {
		return nil, nil, err
	}

NOTE: When I am using same function with q as queryParam I am able to get results. There is an issue with just search method.

**Comment by bogdanprodan-okta** [comment]
Hi @gbhatiaRV! Thanks for submitting this issue! Do you have `proxyAddresses` profile property defined for your users?
I've tried this and it works fine, because `profile.lastName` is standard profile attribute
```
curl --location --request GET 'https://okta.okta.com/api/v1/users?search=profile.lastName eq "A"'
```
More info [here](https://developer.okta.com/docs/reference/api/users/#list-users-with-search)

**Comment by gbhatiaRV** [comment]
Yes, this property is set. I am able to get the results when I hit it through postman.

**Comment by bogdanprodan-okta** [comment]
@gbhatiaRV I've tried this and it worked fine:
```
users, _, err := client.User.ListUsers(context.Background(), &query.Params{Search: `profile.lastName eq "Smith"`})
```

**Comment by gbhatiaRV** [comment]
Thanks for your help @bogdanprodan-okta. Got it resolved and it is working now. 
Thank You!

Issue was:
1. I was using "+" in Search query
2. I used url.QueryEscape in front of query and it worked
