### ISSUE TITLE
Readme is outdated

### ISSUE THREAD

**Issue by ndyment** [okta/okta-sdk-golang#275]
### Describe the bug?

After attempting to use the readme to build some integrations I have noticed the code snippets appear to be based on v1 of the API, which is being deprecated, and not v2.

I have not exhaustively checked each sample, but the 2 that I tried required some rework.

- List users; uses the wrong signature in the sample
- Create user; uses the wrong signature in the sample

### What is expected to happen?

**From example for List Users:**

ctx, client, err := okta.NewClient(context, okta.WithOrgUrl("https://{yourOktaDomain}"), okta.WithToken("{apiToken}"))
users, resp, err := client.User.ListUsers()

### What is the actual behavior?

IDE throws an error: not enough arguments in call to client.User.ListUserscompilerWrongArgCount

### Reproduction Steps?

copy the snippet from the examples into a go application
view error in IDE - application will not compile

![image](https://user-images.githubusercontent.com/9325703/148232165-b9fda0ce-94aa-4f4d-88a4-debbfa1c18f0.png)

### Additional Information?

This can be fixed by following the actual signature of the v2 function, which requires context and query params.

`		ctx, client, err := okta.NewClient(context, okta.WithOrgUrl("https://{yourOktaDomain}"), okta.WithToken("{apiToken}"))
		qp := query.NewQueryParams()
		users, resp, err := client.User.ListUsers(ctx, qp)`

I would suggest that someone try all the samples in the readme and make updates to each for the current version of the SDK (v2.x) in order to have up to date documentation.

### Golang Version

go version go1.17.5 darwin/amd64

### SDK Version

`make: *** No rule to make target `sdk-version'.  Stop.`

but from go.mod
`	github.com/okta/okta-sdk-golang/v2 v2.9.2`

### OS version

Darwin mac-3158 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64

**Comment by arvindkrishnakumar-okta** [comment]
@MikeMondragon-okta can you help take a look please?

**Comment by monde** [comment]
Thanks for pointing this out @ndyment . Can you give me a PR to improve the documentation? That would be a great way improve on the project and give back to the community. Thanks!

**Comment by monde** [comment]
@ndyment strike that PR suggestion! @bretterer is in the process of updating the README. I'll close this issue since it is about to be updated.

**Comment by bretterer** [comment]
@ndyment Thank you for your report here on the documentation. I have reviewed our docs and there are quite a few areas that need to be updated.  I am currently working on updating things from our end and should have a new copy of the readme out in the next few days.

Thank you for your patience and understanding

**Comment by monde** [comment]
@ndyment the README has been cleaned up, @bretterer thanks for cleaning it up.
