### ISSUE TITLE
Support IDP discovery action in Okta

### ISSUE THREAD

**Issue by minwan** [okta/okta-sdk-golang#279]
### Describe the feature request?

It is supported in API but not in SDK, could you add support for it in order to programmatically manage IDP discovery rules? thanks!

https://developer.okta.com/docs/reference/api/policy/#policy-action-object

### New or Affected Resource(s)

IdentityProviderDiscovery

**Comment by laura-rodriguez** [comment]
Hi @minwan,

Thanks for your issue. I created an internal ticket to be prioritized by the team. 

Internal Ref: [OKTA-471081](https://oktainc.atlassian.net/browse/OKTA-471081)

**Comment by monde** [comment]
@minwan I trying to better understand the ask here. Can you show me an example of your API call and payload? I'm assuming you've already verified the behavior experimenting with curl/postman. I'm trying to see if okta-sdk-golang already supports what you are trying to do. Thanks

**Comment by minwan** [comment]
Hi @monde, thanks for quick attention on this issue, here is a sample request 

POST /api/v1/policies/<redacted>/rules HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: SSWS <redacted>
User-Agent: PostmanRuntime/7.28.4
Postman-Token: <redacted>
Host: <redacted>
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 650
Cookie: JSESSIONID=<redacted>
 
{
"type": "IDP_DISCOVERY",
"name": "Test",
"conditions": {
"network": {
"connection": "ANYWHERE"
},
"userIdentifier": {
"patterns": [
{
"matchType": "CONTAINS",
"value": "<redacted>",
}
],
"type": "ATTRIBUTE",
"attribute": "login"
}
},
"actions": {
"idp": {
"providers": [ {
"id": "<redacted>,
"type": "SAML2"
}
]
}
}
}
 
HTTP/1.1 200 OK
Date: Wed, 16 Feb 2022 18:23:32 GMT
Server: nginx
Content-Type: application/json
Vary: Accept-Encoding
x-okta-request-id: Yg1BJNVZFUTXt6puVPxccAAADpY
x-xss-protection: 0
p3p: CP="HONK"
x-rate-limit-limit: 1000
x-rate-limit-remaining: 999
x-rate-limit-reset: 1645035872
cache-control: no-cache, no-store
pragma: no-cache
expires: 0
expect-ct: report-uri="https://oktaexpectct.report-uri.com/r/t/ct/reportOnly", max-age=0
x-content-type-options: nosniff
Strict-Transport-Security: max-age=315360000; includeSubDomains
Content-Encoding: gzip
set-cookie: sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
set-cookie: autolaunch_triggered=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
set-cookie: JSESSIONID=<redacted>; Path=/; Secure; HttpOnly
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Transfer-Encoding: chunked
 
{"id":"<redacted>","status":"ACTIVE","name":"Test","priority":9,"created":"2022-02-16T18:23:32.000Z","lastUpdated":"2022-02-16T18:23:32.000Z","system":false,"conditions":{"network":{"connection":"ANYWHERE"},"userIdentifier":{"patterns":[{"matchType":"CONTAINS","value":"<redacted>"}],"type":"ATTRIBUTE","attribute":"login"},"app":{"include":[],"exclude":[]}},"actions":{"idp":{"providers":[{"id":"<redacted>","type":"SAML2"}]}},"_links":{"self":{"href":"<redacted>","hints":{"allow":["GET","PUT","DELETE"]}},"deactivate":{"href":"<redacted>","hints":{"allow":["POST"]}}},"type":"IDP_DISCOVERY"}

**Comment by monde** [comment]
@minwan I think you can get there with `CreatePolicyRule` https://github.com/okta/okta-sdk-golang/blob/master/okta/policy.go#L142-L164 and `NewIdentityProviderPolicy` https://github.com/okta/okta-sdk-golang/blob/master/okta/identityProviderPolicy.go#L44-L48

```go
func (m *PolicyResource) CreatePolicyRule(ctx context.Context, policyId string, body PolicyRule) (*PolicyRule, *Response, error)
```

```go
func NewIdentityProviderPolicy() *IdentityProviderPolicy
```

**Comment by monde** [comment]
Apologies @minwan, I referenced the wrong struct and code.

Have you tried creating a `PolicyRule` https://github.com/okta/okta-sdk-golang/blob/master/okta/policyRule.go#L29-L40 struct that is a parameter to `CreatePolicyRule`? The `PolicyRule` has `Actions` on it, etc.

```go
func (m *PolicyResource) CreatePolicyRule(ctx context.Context, policyId string, body PolicyRule) (*PolicyRule, *Response, error)
```

something like
```go
body := okta.PolicyRule{
    Type: "IDP_DISCOVERY",
    Name: "test",
    Conditions: &okta.PolicyRuleConditions{
        // ...
    },
    Actions: &okta.PolicyRuleActions {
        // ...
    },
}

// 

rule, resp, err := client.Policy.CreatePolicyRule(ctx, policyId, body)
```

Let me know.

**Comment by minwan** [comment]
Yes, but again PolicyRuleActions does not support IDP actions, which is the ask here.

**Comment by monde** [comment]
ok, I see the ask now @minwan 

This is our spec to generate the code for `PolicyRuleActions` https://github.com/okta/okta-management-openapi-spec/blob/master/dist/spec.yaml#L13813-L13827:
```yaml
  PolicyRuleActions:
    properties:
      enroll:
        $ref: '#/definitions/PolicyRuleActionsEnroll'
      passwordChange:
        $ref: '#/definitions/PasswordPolicyRuleAction'
      selfServicePasswordReset:
        $ref: '#/definitions/PasswordPolicyRuleAction'
      selfServiceUnlock:
        $ref: '#/definitions/PasswordPolicyRuleAction'
      signon:
        $ref: '#/definitions/OktaSignOnPolicyRuleSignonActions'
    type: object
    x-okta-tags:
      - Policy
```

and it needs an action for idp, something like:

```yaml
      idp:
        $ref: '#/definitions/IdpPolicyRuleAction'
```

With that, our golang code generation would get a `IdpPolicyRuleAction`. 

We are in the process of changing how we manage our API spec and code generation in the next month. With that, all of the SDK would get a major bump to version `3.*.*`. I can see that the v3 spec is also missing a `IdpPolicyRuleAction`. I need to consult with our team if we want to do a patch release v2.10.2 or wait for the v3 release. I'll follow up when I get more information.

**Comment by minwan** [comment]
Thanks, @monde it would be great if we can get a V2 patch since we've been using V2 in many production flows and trying to reduce the upgrade cost.

**Comment by monde** [comment]
All right @minwan , we'll be doing a `v2.11.0` release with the update for `IdpPolicyRuleAction`. I should have something with a day.

**Comment by monde** [comment]
@minwan can you double check these models for me? `IdpPolicyRuleAction` and `IdpPolicyRuleActionProvider`
https://github.com/okta/okta-sdk-golang/pull/280

I'm waiting for feedback from the SDK owners feedback in Okta DevEx

**Comment by monde** [comment]
There will be more bits in a v2.11.0 release, including email templates, waiting for the openapi spec https://github.com/okta/okta-management-openapi-spec/pull/117 to be released.

**Comment by minwan** [comment]
Thanks, @monde for the quick addition! I think we can wait for the release but will also try the branch out first.

**Comment by monde** [comment]
ok @minwan v2.11.0 is released https://github.com/okta/okta-sdk-golang/releases/tag/v2.11.0
