### ISSUE TITLE
Stale cached list responses

### ISSUE THREAD

**Issue by Nick-Triller** [okta/okta-sdk-golang#284]
### Describe the bug?

Cached list responses are not invalidated when an item is deleted, modified or created.

### What is expected to happen?

List calls should not return stale items after delete / update / create calls.

### What is the actual behavior?

List calls return stale items after delete / update / create calls.

### Reproduction Steps?

In a program using the SDK, perform the following steps:
- List applications
- Delete an application
- List applications

The second list result still contains the deleted application. Looking at the SDK code, the same should happen for other domain objects and with creation / modification instead of deletion, but I did not verify it.

### Additional Information?

Disabling the cache, clearing the cache manually or using low cache TTL / TTI are potential workarounds in some situations.

### Golang Version

go version go1.17.1 darwin/amd64

### SDK Version

Version from go.mod: `github.com/okta/okta-sdk-golang/v2 v2.11.0`

**Comment by monde** [comment]
@Nick-Triller how fast are you doing this list, delete, list operation? You might have experienced a replication lag in Okta's core RDMS, but I'm waiting to hear internally what a reasonable replication lag might be.

**Comment by ntriller-plaid** [comment]
@monde Are you sure there is no client side caching? Instantiating the client with [okta.WithCache(false)](https://github.com/okta/okta-sdk-golang/blob/acdc6d6a468bfb64892d211ff38902da062be7cb/okta/config.go#L70) fixed the issue for me. It seems the cache is read / written in https://github.com/okta/okta-sdk-golang/blob/master/okta/requestExecutor.go#L250

**Comment by monde** [comment]
@Nick-Triller I was not aware of the caching in the request executor, apologies on my false assertion about caching. That caching code seems complicated and can't defend against operation done in parallelism. I will look into this further. Also, we have seen internal integration tests in the Okta SDKs experience replication issues from Okta core, so I'm looking for some internal experience on what a reasonable replication lag duration to be. I will report back what I find.

**Comment by monde** [comment]
@Nick-Triller follow up. I did hear back internally. The Okta core does reads against db read replicas. So, if you have okta-sdk-golang in cache false mode (which is the default without setting it) [okta.WithCache(false)](https://github.com/okta/okta-sdk-golang/blob/acdc6d6a468bfb64892d211ff38902da062be7cb/okta/config.go#L70) you might experience an inconsistency between a delete and subsequent read (e.g. list, delete item, list again has deleted item). There wasn't an SLA on how much time this might be, could be a second +/-. As I said, some of our SDK integration tests have a sleep to protect against eventual consistency when testing around delete then read.

I suspect there is a bug in okta-sdk-golang when cache is enabled where it doesn't correctly invalidate its request/response cache based on HTTP method and URI path in the request executor https://github.com/okta/okta-sdk-golang/blob/65b07d6dbc17c0a9344cd050666c7fef73be6100/okta/requestExecutor.go#L249-L272 . I need to work on that bug.

TODO / note to self:
* fix internal caching in okta-sdk-golang
* add caching information in README

**Comment by Nick-Triller** [comment]
Thanks for getting back to me! Small correction, the cache is enabled by default according to [okta.go](https://github.com/okta/okta-sdk-golang/blob/65b07d6dbc17c0a9344cd050666c7fef73be6100/okta/okta.go#L168). I agree there is a bug in the invalidation, the endpoint for listing something is `/something/` while create / delete is `/something/<id>`, so the cache keys are different.

**Comment by monde** [comment]
🤦 https://github.com/okta/okta-sdk-golang/blob/master/okta%2Fokta.go#L168
```go
func setConfigDefaults(c *config) {
	conf := []ConfigSetter{
		WithConnectionTimeout(60),
		WithCache(true),
```

**Comment by monde** [comment]
@Nick-Triller working on this issue as helped me get better acquainted with okta-sdk-golang. I have an update for the README that will go in the next release that explains the config setter and the client's default settings.

That said, there isn't a bug in the memory cache. As the cache is simple; if you are using the memory cache and do a list operation, then delete an item that would be in that list, then do a list operation again the memory cache for the list won't be expired by the delete. Make use of RefreshNext for this situation. See https://github.com/okta/okta-sdk-golang#refreshing-cache-for-specific-call . Which makes me think we should have caching be off by default. For instance, Okta's Terraform provider is written in Go and make use of okta-sdk-client with a disabled memory cache (see https://github.com/okta/terraform-provider-okta/blob/d40aa071ca835e89051b07875ae2010ef03b4ba5/okta/config.go#L99 )

From the example:

```go
appUserList, resp, err := client.Application.ListApplicationsUsers(ctx, nil)

client.Application.DeleteApplicationUser(context.TODO(), appId, appUser.Id, nil)

client.CloneRequestExecutor().RefreshNext()
appUserList, resp, err := client.Application.ListApplicationsUsers(ctx, nil)
```

I'll close this ticket for now and ask around internally why we set caching on by default.
