### ISSUE TITLE
Request to reopen issue #293

### ISSUE THREAD

**Issue by pputman12** [okta/okta-sdk-golang#297]
### Describe the bug?

Please see issue #293 While I thought this was fixed, its because its intermittent.  testing several more times with query caching disabled, and still receiving the same issue.

### What is expected to happen?

See issue #293

### What is the actual behavior?

See issue #293

### Reproduction Steps?

Please see issue #293

### Golang Version

go 1.18.1

### SDK Version

latest

**Comment by monde** [comment]
I missed this issue @pputman12 , I will take a look at it again.

**Comment by monde** [comment]
Re-opened #293 and will track work there
