### ISSUE TITLE
Plan for Okta terraform provider

### ISSUE THREAD

**Issue by tsiq-hanyu** [okta/okta-sdk-golang#32]
Hi,

I am wondering if okta has any plans or schedule on releasing a terraform provider for okta management. Since terraform providers are in golang this might be a good place to ask this question. 

Thanks!

**Comment by nbarbettini** [comment]
Thanks for the question @tsiq-hanyu! We don't have concrete plans to build a Terraform provider (yet), but it is something I am looking at for the roadmap.

Please keep 👍ing the above post if you are interested in Terraform!

**Comment by quantumew** [comment]
There is one still in development https://github.com/articulate/terraform-provider-okta. Uses a non-official SDK where this SDK does not yet have functionality. Although an official provider would be great 👍

**Comment by chrismorris-okta** [comment]
There's an open-source terraform provider for Okta here. This is certified by Hashicorp.  https://github.com/terraform-providers/terraform-provider-okta/

**Comment by bretterer** [comment]
Closing this as stale.  We are working on providing a terraform provider, but do not currently have a timeline for the officially supported version. You can use the community driven one for now and can find it at https://github.com/oktadeveloper/terraform-provider-okta
