### ISSUE TITLE
Using gopkg.in/yaml.v2 vs github.com/go-yaml/yaml

### ISSUE THREAD

**Issue by tsiq-hanyu** [okta/okta-sdk-golang#34]
Hi,

It seems that currently this repo depends on `github.com/go-yaml/yaml`, while the [document](https://github.com/go-yaml/yaml) for `go-yaml` suggests using `gopkg.in/yaml.v2`. This is causing problems with `govendor`:

```
go build
# github.com/<...>/vendor/github.com/go-yaml/yaml
vendor/github.com/go-yaml/yaml/error.go:4:2: "ERROR: the correct import path is gopkg.in/yaml.v2 ... " evaluated but not used
```

Best,
Hanyu

**Comment by bretterer** [comment]
We are using github.com url because we are using `dep` for dependency management.  Is this an error caused by the SDK here, or a limitation of go-yaml?

**Comment by tsiq-hanyu** [comment]
Hi @bretterer , thank you so much for responding to this! Yes, it seems that this is a limitation of `go-yaml`. The project explicitly discouraged importing using the github link. I am glad to know this is not cause trouble for `dep`. 

Reference:  https://github.com/go-yaml/yaml/issues/349

**Comment by bretterer** [comment]
Is this a blocker for you using our SDK to where we need to look at making this work with gopkg.in?
