### ISSUE TITLE
Okta client caching causes EOF errors

### ISSUE THREAD

**Issue by tsiq-kylel** [okta/okta-sdk-golang#36]
When developing with the `Client` in https://github.com/okta/okta-sdk-golang/blob/master/okta/okta.go#L29, I noticed that repeated GETs to the same endpoint would result in `Unexpected EOF` errors. I was passing in a pointer to a struct to unmarshal the response into.

This behavior disappeared when I disabled caching in the client config. `.WithCache(false)`

**Comment by bretterer** [comment]
This has been addressed in #134

**Comment by bretterer** [comment]
If you are still seeing an error here, please reach back out
