### ISSUE TITLE
Proxy support not implemented

### ISSUE THREAD

**Issue by viktor-yengovatov** [okta/okta-sdk-golang#38]
in `requestExecutor.go`:
```
if httpClient == nil {
		tr := &http.Transport{
			IdleConnTimeout: 30 * time.Second,
		}
		re.httpClient = &http.Client{Transport: tr}
	}
```

there no Proxy configured for Transport (`tr`)

**Comment by nbarbettini** [comment]
Hi @viktor-yengovatov, sorry for the long delay in responding. We're planning some work to make the Go SDK easier to use. If you were able to pass an already-constructed HTTP client (see #54) would that unblock you here?

Just curious, what do you need to configure a proxy for?

**Comment by tsiq-hanyu** [comment]
I encounter the same issue. I want to pass in a custom http client with special logging enabled.

**Comment by ykumar-rb** [comment]
You can do something like:

              proxyUrl, _ := url.Parse("http://XX.XX.XX:8080")
              tr := &http.Transport{
                             IdleConnTimeout: 30 * time.Second,
                             Proxy: http.ProxyURL(proxyUrl),
              }
              httpClient := &http.Client{Transport: tr}
              client := okta.NewClient(config, httpClient, nil)

It works for proxy

**Comment by bretterer** [comment]
You can now pass in a custom http client into the okta client with the release of v1.0.0
