### ISSUE TITLE
Cannot create a three field SWA app

### ISSUE THREAD

**Issue by quantumew** [okta/okta-sdk-golang#39]
https://github.com/okta/okta-sdk-golang/blob/develop/okta/swaThreeFieldApplicationSettingsApplication.go#L29

Should be targetURL. Looks like the openapi spec is wrong. Not sure why some are Url but others are URL but that appears to be the way the API is. Docs are actually wrong too

https://developer.okta.com/docs/api/resources/apps#add-plugin-swa-3-field-application

The API returned an error: Api validation failed: targetURL. Causes: errorSummary: targetURL: The field cannot be left blank

**Comment by nbarbettini** [comment]
You're right, this is a bug in our docs as well. `targetURL` is correct. Sorry about that! Looking into it. Thanks for the PR 🙂

**Comment by bretterer** [comment]
@quantumew Thanks for you report here.  This is tagged to be fixed in v2.0.0

**Comment by bretterer** [comment]
This has been fixed in v2.0.0.   Please let us know if you have any other issues here.
