### ISSUE TITLE
Clean up README examples, update to v3 version of SDK

### ISSUE THREAD

**Issue by monde** [okta/okta-sdk-golang#406]
### Describe the bug?

The README needs to be updated to reference v3 version of the SDK.

Also, take this opportunity to clean up the README in general.

### What is expected to happen?

Have a concise and accurate README.

### What is the actual behavior?

v2 SDK is obsolete and still referenced.

### Reproduction Steps?

Read the README.

### Golang Version

any

### SDK Version

any

**Comment by duytiennguyen-okta** [comment]
This is update via #427
