### ISSUE TITLE
Add User-Agent header to `POST /oauth2/v1/token` OAuth token request

### ISSUE THREAD

**Issue by monde** [okta/okta-sdk-golang#408]
### Describe the bug?

The `POST /oauth2/v1/token` OAuth token request is not adding a User-Agent header as occurs with all other API requests.

Perhaps add a unit test for this.

### What is expected to happen?

User-Agent header added

### What is the actual behavior?

It isn't added

### Reproduction Steps?

Make an OAuth request

### Golang Version

any

### SDK Version

all

**Comment by duytiennguyen-okta** [comment]
internal reference https://oktainc.atlassian.net/browse/OKTA-658719

**Comment by m3talsmith** [comment]
@monde I'm curious where this is happening myself. I dove through the code some and found that code calling the `(*RequestExecutor).NewRequest(...)` method always gets the [UserAgent assigned](https://github.com/okta/okta-sdk-golang/blob/master/okta/requestExecutor.go#L413). It might be a matter of that method not being called at one point in the API.

Deep diving here to see what I can come up with.

**Comment by m3talsmith** [comment]
It could also be in that same file in [this function](https://github.com/okta/okta-sdk-golang/blob/master/okta/requestExecutor.go#L273) which is autogenerated.

**Comment by monde** [comment]
> It could also be in that same file in [this function](https://github.com/okta/okta-sdk-golang/blob/master/okta/requestExecutor.go#L273) which is autogenerated.

Yes, for the v3 client in the template you've referenced.

The v2 okta-sdk-golang client is vendor'd into the okta terraform provider, this where I hacked that in:
https://github.com/okta/terraform-provider-okta/blob/master/sdk/v2_requestExecutor.go#L295C40-L295C40
