### ISSUE TITLE
Cannot ListApplications on develop

### ISSUE THREAD

**Issue by quantumew** [okta/okta-sdk-golang#41]
Consistently returns an unmarshalling error.

**Comment by hyzhangsf** [comment]
I confirm this issue.

**Comment by tsiq-hanyu** [comment]
I confirm this issue.

**Comment by bretterer** [comment]
I believe this should be resolved now. With the release of 1.0.0, there were some changes to the application spec.

Please feel free to re-open this ticket or create a new one if it is still an issue
