### ISSUE TITLE
publish v3 generated docs

### ISSUE THREAD

**Issue by monde** [okta/okta-sdk-golang#413]
### Describe the feature request?

We should be publishing the markdown generated SDK docs that are produced during v3 code gen. I'm not sure of the best way to hack this into GH. Perhaps in a dist/ directory in the repo, or the default wiki each GH repo comes with.

### New or Affected Resource(s)

new docs

**Comment by tgoodsell-tempus** [comment]
@monde You may also want to checkout the "publish" patterns for the go docs when doing a module publish. You probably can just funnel all that stuff into https://pkg.go.dev/github.com/okta/okta-sdk-golang/v3/okta#readme-overview and have it be the display page for you.

**Comment by monde** [comment]
Never mind, as @tgoodsell-tempus points, we are already getting this for free in go package distribution https://pkg.go.dev/github.com/okta/okta-sdk-golang/v3/okta
