### ISSUE TITLE
release v3.0.17

### ISSUE THREAD

**Issue by monde** [okta/okta-sdk-golang#414]
### Describe the feature request?

There is a new OAS3 version that has `FLEXIBLE` enum value added to oauth2 consent to support the issue discussed https://github.com/okta/okta-management-openapi-spec/pull/179 . Let release a v3.0.17 version of okta-sdk-golang so we can get it downstream to the TF provider.

### New or Affected Resource(s)

new release

**Comment by duytiennguyen-okta** [comment]
Close with #417
