### ISSUE TITLE
Support Authorization Server API

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-golang#42]
This API is currently not supported by this library: https://developer.okta.com/docs/api/resources/authorization-servers

Please 👍  this issue if you are interested in using this SDK to manage Authorization Server resources.

In the meantime, you can use this generic syntax to call any API (including the AS API): https://github.com/okta/okta-sdk-golang#call-other-api-endpoints

**Comment by nbarbettini** [comment]
@BrentSouza Yeah, the spec file is in a private repo, so we can't accept PRs for that. Anything else we're happy to look at contribs for!

**Comment by bretterer** [comment]
This is resolved by [v2.0.0-rc.1](https://github.com/okta/okta-sdk-golang/releases/tag/v2.0.0-rc.1)

If this is still an issue, please open a new ticket explaining what is going on.
