### ISSUE TITLE
API Rate limits

### ISSUE THREAD

**Issue by quantumew** [okta/okta-sdk-golang#43]
Are there any plans to build in retry/backoff logic when 429's occur? Caching will help for sure but curious if there will be further measures put in place for API Rate limiting?

**Comment by bretterer** [comment]
Hey @quantumew.  Rate limit/retry is on our roadmap now.  It will be released in a future release of the library.

**Comment by agiles231** [comment]
I have written a solution called proktasy that acts a proxy between Okta REST API clients and Okta. It is easily deployed using Tomcat and resolves all rate limiting issues. Also, an SDK would have a difficult time accounting for rate limiting produced by other applications, even if using the same SDK. proktasy solves that too. Let me know if this does what you want.

**Comment by jeffg-hpe** [comment]
I would like to see the go sdk be proactive about backoff based on [rate limit headers](https://developer.okta.com/docs/reference/rate-limits/#check-your-rate-limits-with-okta-s-rate-limit-headers).  Rather than waiting for a `429` to occur.

**Comment by chrismorris-okta** [comment]
hey @quantumew. We've added this in release 1.1.0. Here's the PR. Thanks for opening the issue. https://github.com/okta/okta-sdk-golang/pull/93
