### ISSUE TITLE
Client assertion token does not have a jti claim, making it reusable

### ISSUE THREAD

**Issue by clementdenis** [okta/okta-sdk-golang#458]
### Describe the bug?

The ClientAssertionClaims struct in client.mustache has an ID field (jti claim)

https://github.com/okta/okta-sdk-golang/blob/097ef410838011d464266aa06e5fb720c9c7d6c2/.generator/templates/client.mustache#L1206-L1213

 but this is not used in createClientAssertion

https://github.com/okta/okta-sdk-golang/blob/097ef410838011d464266aa06e5fb720c9c7d6c2/.generator/templates/client.mustache#L349-L359

### What is expected to happen?

The client assertion token should have a jti claim to prevent reuse.

### What is the actual behavior?

The client assertion token can be used multiple times.

### Reproduction Steps?

N/A

### Additional Information?

The other SDKs add a jti claim:
- [Python](https://github.com/okta/okta-sdk-python/blob/f8d7bd185eb90771da7973968da7ac4f110d90a1/okta/jwt.py#L125)
- [Java](https://github.com/okta/okta-sdk-java/blob/5abbeb69f73d3ab5639065058914ba833685085c/impl/src/main/java/com/okta/sdk/impl/oauth2/AccessTokenRetrieverServiceImpl.java#L191)

### Golang Version

Any

### SDK Version

Latest

**Comment by duytiennguyen-okta** [comment]
https://oktainc.atlassian.net/browse/OKTA-733548
