### ISSUE TITLE
Function signatures improvement suggestion

### ISSUE THREAD

**Issue by thylong** [okta/okta-sdk-golang#48]
Hello dear maintainer!

First of all, thanks a lot for working on an open source Go SDK for the Okta API ! That's going to help a lot of companies such as BackMarket.

I opened the PR #47 recently and wondered if you're opened to suggestion in term of fucntion signature design.

As I work pretty heavily in Go and BackMarket in general is moving that way,  we're going to use Okta more and more and it would be a pleasure to work hands to hands on that when we can afford the time to.

As you're in beta, One of the thing that could make a huge difference is to handle response checks (status, body, etc) in the SDK and have signatures change from for example:
`user, resp, err := client.User.CreateUser(*u, nil)`
to
`user, err := client.User.Create(*u, nil)`

This would drastically reduce the complexity related to error handling on the developer side.
What do you think?

Thanks again for your work,
Best regards

**Comment by basement199** [comment]
I agree with this. Just return err and whatever the caller asked for, you can handle the response checks inside the functions. I think that is more idiomatic Go.    I built my own Okta Go SDK.   A small sample of what it looks like below.
   
Glad you are working on this, I will keep an eye on it.   

`package main

import (
	"fmt"
	"os"

	"github.com/user/OktaSDK/errors"
	"github.com/user/OktaSDK/users"
)

func main() {

	apiKey := os.Getenv("OKTA_PROD_KEY")
	oktaOrg := os.Getenv("OKTA_PROD_ORG")

	userClient := users.NewUserClient(oktaOrg, apiKey)

	users, err := userClient.GetAllUsers()

	if err != nil {
		if detailedErr, ok := err.(errors.OktaError); ok {
			fmt.Println(detailedErr.ErrorCode)
			fmt.Println(detailedErr.ErrorSummary)
			for _, errorCause := range detailedErr.ErrorCauses {
				fmt.Println(errorCause.ErrorSummary)
			}
		} else {
			fmt.Println(err.Error())
		}
	}

	for _,  user := range users {

		login := user.Profile.Login
		eMail := result.Profile.Email


	}

}
`
thanks.

**Comment by quantumew** [comment]
I disagree but I might be missing something. Would each result struct implement a `Response()` method that allows me access to the underlying `http.Response`? What if I want to implement back off/retries when I hit API rate limits? I would need access to the headers and status code. Also, I would just generally want the status code so I could react to certain situations uniquely. I do agree in most cases this more idiomatic approach is suitable but unless there is a way to access the response it would make it more inflexible.

**Comment by thylong** [comment]
Hey @quantumew, thanks for adding your thoughts to this issue, really appreciated 😊 

The idea behind the idiomatic error handling approach that I suggested is to also expose clear error types (or `const`s) when any CRUD operation fails.

That way, you can completely do type assertion on your errors and determine what the underlaying problem. More on that : https://gobyexample.com/errors

In the rate limit hit case that you mention, this would become : `
// RateLimitError occurs when the rate limit has been hit
type RateLimitError struct {     arg  int     prob string }
--
  | func (e *RateLimitError) Error() string {     return fmt.Sprintf("%d - %s", e.arg, e.prob) }
`

> You could figure out what ErrorCode mapped to what StatusCode or expose a map but I would prefer not to unless there was a compelling reason

Even though I agree with the fact that HTTP statuses are easy to deal with, if the implementation returns statuses and let developers handle it, this SDK will be deeply coupled to the API exposed by Okta, making virtually almost impossible API evolution without breaking changes.
That being said, if all errors are typed correctly (which is not that much of a pain to implement) you will still be able to react to certain situations uniquely, with the same flexibility and a less verbose error handling on your side.

**Comment by quantumew** [comment]
Thanks for the detailed explanation. That makes sense, if implemented correctly it would maintain the same flexibility.

**Comment by BrentSouza** [comment]
As far as the method names, I made a couple of basic additions to the generator template that can help. 

`openapi/generator/index.js`
```js
function getMethodName(modelName, string) {
  var regex = new RegExp("(?:(To|From))?" + modelName + "s?")
  return ucFirst(string.replace(regex, ""))
}
...
// then register it so it can be used in the templates
handlebars.registerHelper({
    getType,
    structProp,
    log,
    ucFirst,
    operationArgumentBuilder,
    getPath,
    getPathParams,
    getMethodName,
...
```

`openapi/generator/templates/model/defaultMethod.go.hbs`
```hbs
func (m *{{modelName}}Resource) {{getMethodName modelName operation.operationId}}({{operationArgumentBuilder operation}}) {{returnType
```

Since the ModelName is used in all of the operationIds within the spec.json, this universally changes the method names to remove the redundant resource name, examples:

```go
// before
func (m *UserResource) CreateUser(body User, qp *query.Params) (*User, *Response, error) {}
// after
func (m *UserResource) Create(body User, qp *query.Params) (*User, *Response, error) {}
// before
func (m *UserResource) ListUsers(qp *query.Params) ([]*User, *Response, error) {}
// after
func (m *UserResource) List(qp *query.Params) ([]*User, *Response, error) {}
// before
func (m *UserResource) AddRoleToUser(userId string, body Role) (*Role, *Response, error) {}
// after
func (m *UserResource) AddRole(userId string, body Role) (*Role, *Response, error) {}
// before
func (m *UserResource) RemoveRoleFromUser(userId string, roleId string) (*Response, error) {}
// after
func (m *UserResource) RemoveRole(userId string, roleId string) (*Response, error) {}
```

I'm happy to open a pull request for this change if it's acceptable

**Comment by nbarbettini** [comment]
Thanks for the discussion everyone! Sorry for the long delay in responding. We had to work on some other things, but are circling back around to getting the Go SDK from beta to stable. All of your feedback is very helpful! Feel free to post any more of it, or shoot me an email at nate.barbettini@okta.com.

@thylong @basement199 Other than `RateLimitError`, what other errors would you want to see strongly-typed?

**Comment by paulquerna-okta** [comment]
At this point, all of the function signatures should take `context.Context` as a first parameter and propagate that down to the http client as its making requests -- the idiomatic use of context.Context is now pretty common in Go compared to when this issue was first opened

**Comment by bretterer** [comment]
So, we have been doing a lot of work on the SDK lately.  In v2.0.0 (which is in RC state at the moment), we introduced `context.Context` to all methods.  At this point, we are not going to be modifying the method names to remove the resource name at this time due to some other requirements we have.
We do plan to continue returning all three (the object, response, and error) for all methods that require it so you can use the response itself for some other purposes if you need.  I do not like to hide any of this anywhere. We do wrap the `response` in our own response object. so you should be able to use it as well as anything else we add there.
