### ISSUE TITLE
Cannot set application settings

### ISSUE THREAD

**Issue by quantumew** [okta/okta-sdk-golang#52]
It is not possible to set Application settings when creating or updating an application due to the spec definition resulting in a struct without any attributes. Instead of a struct with no fields it should be `map[string]interface{}`. 

This brings up a question is development on this library dead? Is there any future plans of continuing it? Just trying to decide how much time to put into a fork.

https://github.com/okta/okta-sdk-golang/blob/master/openapi/spec.json#L3879
https://github.com/okta/okta-sdk-golang/blob/master/okta/applicationSettingsApplication.go#L23

**Comment by bretterer** [comment]
Hey @quantumew .

Sorry for the lack of updates here.  We are continuing work on the SDK now and this is on our roadmap to look at.  Standby.

-Brian

**Comment by quantumew** [comment]
Awesome! Maintaining a fork has worked well. I wasn’t aware of the request executor being exposed at this point. That made things easy.

**Comment by bretterer** [comment]
Would love to see what you have done with your fork for the few items you mentioned.   could you point me to your fix for this as well as the other changes you have made that would love to see in a 1.0 release?

**Comment by quantumew** [comment]
Here is the fork comparison. Not sure how useful it will be (some cases I think the generated code was edited) but it mostly allowed me to get past some bugs. Also added some support for retries and exponential backoffs when the API returns 429s.
https://github.com/okta/okta-sdk-golang/compare/develop...articulate:master

**Comment by bretterer** [comment]
Coming back to this bug here.  Can you give me an example of when you would work directly with an instance of `applicationSettingsApplication` and not one of the specific application settings structs.  IE, you have a `Bookmark Application` and it has a related `bookmarkApplicaitonSettingsApplication`

**Comment by quantumew** [comment]
When creating a SAML App https://github.com/okta/okta-sdk-golang/blob/develop/okta/samlApplicationSettings.go#L24

**Comment by bretterer** [comment]
This should now be resolved.
