### ISSUE TITLE
SAML Attribute Statement is wrong type

### ISSUE THREAD

**Issue by quantumew** [okta/okta-sdk-golang#53]
SAML Attribute statements are not hooked up properly in the spec. It is of type `[]string` which is incorrect, it should be `[]*SamlAttributeStatement`.

https://developer.okta.com/docs/api/resources/apps#attribute-statements-object
https://github.com/okta/okta-sdk-golang/blob/master/openapi/spec.json#L5685
https://github.com/okta/okta-sdk-golang/blob/master/okta/samlApplicationSettingsSignOn.go#L25
https://github.com/okta/okta-sdk-golang/blob/master/okta/samlAttributeStatement.go

**Comment by bretterer** [comment]
This has now been updated in v2.0.0.  Please let us know if you are still experiencing an issue with this by opening a new ticket with your concerns.
