### ISSUE TITLE
client.User.ListUsers() only lists users up to the default limit

### ISSUE THREAD

**Issue by adenix** [okta/okta-sdk-golang#57]
client.User.ListUsers() only lists up to the default limit. The README.md states that the method should list all users.

**Comment by quantumew** [comment]
The API is paginated, with next/prev links in the link header. This is modulated with the `after` and `limit` query params. You can call ListUsers recursively until you run out of `after` links, with each subsequent call, you of course send the `after` param parsed from the link header. Not a maintainer but I believe that would be the recommended approach.

**Comment by adenix** [comment]
I know they use the `Link` header to provide the next page link. Just calling out an inconsistency based off how the Okta NodeJS SDK operates.

**Comment by quantumew** [comment]
Good deal, to be clear this isn't an inconsistency in how `ListUsers` works but rather a missing feature. The Node SDK implements the idea of a collection, which simply abstracts the pagination code. That may have been what you meant, just clarifying, I agree though, implementing a similar pagination abstraction for all List endpoints would be pretty handy. It would definitely work in an  different manner though, being that Go is quite different then Node.

**Comment by nbarbettini** [comment]
Thanks for pointing it out @adenix. @quantumew is correct, this is an extra feature we added to the Node SDK that we haven't yet added here. Right now the Go SDK is pretty "low level" but we will consider doing this in the future if everyone thinks it would be useful.

I made a PR to clarify the documentation here: https://github.com/okta/okta-sdk-golang/pull/58

**Comment by johnathansult** [comment]
Commenting to vote for this feature. The "fetch all users" documentation combined with the lack of pagination caused an outage for us.

**Comment by msiuts** [comment]
Is this project actively maintained by Okta? The PR for the documentation update is unhandled, the nightly build is failing and in general it feels like most of the issues are not addressed in a timely fashion.

According to the Readme this project is "released", but it is not mentioned on https://developer.okta.com/code/library-versions/#current-versions and on this page there is no definition for "relased" - only for "stable".

**Comment by bretterer** [comment]
We now have the idea of `next()` on the resource. this allows you to iterate through each item in your response, and then call `next()` to get the next set for you.

to see if your response has a next page, you can call `hasNext := resp.HasNextPage()`.  if this returns `true` you can then call

```go
var user2 []*okta.User
resp, err = resp.Next(ctx, &user2)
```

this will return your next set of users (or whatever your list is in the first place.

If you still have issues, please come back and re-open this issue.

**Comment by payneWeave** [comment]
I have a client application that is supposed to list users on the frontend. We are proxying our calls through a Go service. What is the recommended way to do pagination with this SDK? It seems like I'd just call `Next` over and over till I've gotten all my users. But what if I need to do pagination on my client? Can I call ListUsers and specify my offset and limit?

**Comment by bretterer** [comment]
Hi @payneWeave. You can set limit and offset with the query parameters.

This will show you how to do Limit: https://github.com/okta/okta-sdk-golang#pagination

Offset is similar to this, but with `query.WithAfter`.  

For documentation on this, please see: https://developer.okta.com/docs/reference/api-overview/#pagination
