### ISSUE TITLE
How to introspect user tokens?

### ISSUE THREAD

**Issue by mcandre** [okta/okta-sdk-golang#64]
Hi, I am curious about interacting with the Okta API via okta-sdk-golang. Which Go methods provide the `/introspect` endpoint, or the `/.well-known/openid-configuration` endpoint, so that user tokens can be verified.

I see the separate okta/okta-jwt-verifier-golang library, but I wonder if the main Okta Go SDK could also provide this functionality. Would it make sense for both Okta applications and Okta administrators to use this SDK?

**Comment by bretterer** [comment]
Hi @mcandre. We do not have a plan to include the introspect endpoint since we maintain the okta-jwt-verifier package for golang as you suggested.

Is there a reason that you could not use the jwt verifier as well as the sdk?

**Comment by monde** [comment]
I'm going to close this issue. @mcandre please reopen if https://github.com/okta/okta-jwt-verifier-golang doesn't provide the feature you are looking for.
