### ISSUE TITLE
Support more client authentication mechanisms

### ISSUE THREAD

**Issue by mcandre** [okta/okta-sdk-golang#67]
I think the main Okta REST API supports HTTP Basic Auth for token revocation requests, is this correct?

https://developer.okta.com/docs/api/resources/oidc/#revoke

However, the Go SDK appears to require SSWS for this. Would it be possible to allow for more Okta client authentication mechanisms, in order to match the same features available in the REST API?

**Comment by bretterer** [comment]
Thank you for your feedback here.  

I will discuss this with the team and will update here as we know more.

**Comment by bretterer** [comment]
@mcandre We now support Oauth 4 Okta in our SDK's. Please see the documentation at https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/overview/ on how to set this up.

If you have any issues, please feel free to come back here and let us know.
