### ISSUE TITLE
Query: When is plan for next merge from develop branch  to master

### ISSUE THREAD

**Issue by ykumar-rb** [okta/okta-sdk-golang#69]
When is plan to merge PULL request : https://github.com/okta/okta-sdk-golang/pull/26/files from develop branch to master. I am mostly stuck at create OIDC application/client, which is fixed here.

**Comment by bretterer** [comment]
Hi @ykumar-rb 
We are in the process of updating some items before we do so.  though I do not have a definite date for this, it is on our short term plan.

Please keep watching the repo for when we do the 1.0.0 release of the sdk

**Comment by groggemans** [comment]
@bretterer I think this can be closed now.

Btw, a big thanks to the devs working on this! (we already use the beta for some production stuff, so we are very happy there's now a v1 release)

**Comment by bretterer** [comment]
Thank you for the feedback here!  It makes us happy when our customers are happy.  Please let us know if anything comes up!

**Comment by ykumar-rb** [comment]
Big Thanks for merging fixes sooner.
