### ISSUE TITLE
Integration tests fail due to no mocks

### ISSUE THREAD

**Issue by zbuc** [okta/okta-sdk-golang#71]
I am working on a project where I need to mock out Okta's API during local development and testing.

I see there are some integration tests present in this repository, but they fail due to no support for mocking Okta API responses.

How do you typically run the integration tests for this project? Do they only support running against a real Okta account?

**Comment by zbuc** [comment]
I see you support passing your own `http.Client`, I am considering creating one that will provide preprogrammed responses for testing and dev purposes.

**Comment by zbuc** [comment]
Hm, this looks like a difficult path because you accept only the `http.Client` struct, and not the `HttpClient` interface :/

**Comment by zbuc** [comment]
I wound up getting this working with the `httptest` class.

**Comment by AdamRussak** [comment]
Hi,
I know it's been a long time, but can you share how you did it?
I need to test v4, and I'm struggling to get started here :(
