### ISSUE TITLE
Missing properties on SAMLAttributeStatement

### ISSUE THREAD

**Issue by quantumew** [okta/okta-sdk-golang#76]
Fix in my fork https://github.com/articulate/okta-sdk-golang/blob/master/okta/samlAttributeStatement.go#L26-L27

Missing here: https://github.com/okta/okta-sdk-golang/blob/master/okta/samlAttributeStatement.go#L23

**Comment by bretterer** [comment]
@quantumew it seems that these properties were not included in our latest revamp of the sdk (v2.0.0).  Can you pinpoint in our documentation where these properties exist as I am not able to find them.

**Comment by bogdanprodan-okta** [comment]
These fields are available in the latest version of Golang SDK.
