### ISSUE TITLE
User credentials emails struct is incorrectly mapped

### ISSUE THREAD

**Issue by maxschae4** [okta/okta-sdk-golang#81]
The UserCredentials struct does not unmarshal due to miss-match between email type and the api return.
https://github.com/okta/okta-sdk-golang/blob/da407cb0985399f7ce98bc06a6fecd00ef7a7482/okta/userCredentials.go#L24
emails is actually an array of json objects like:
```
[
    {"value":"john@example.com","status":"VERIFIED","type":"PRIMARY"},
    {"value":"doe.john@example.com","status":"VERIFIED","type":"SECONDARY"}
]
```
This results in the expected error:
`json: cannot unmarshal object into Go struct field UserCredentials.emails of type string`

**Comment by lwalter** [comment]
+1 this is blocking us writing user management and provisioning pipelines
