### ISSUE TITLE
client.requestExecutor and config are unexported

### ISSUE THREAD

**Issue by quantumew** [okta/okta-sdk-golang#83]
You can no longer follow this code https://github.com/okta/okta-sdk-golang#call-other-api-endpoints. Previously I instantiated requestExecutor directly but since config is unexported you can no longer do this.  Using `client.requestExecutor` also doesn't work because it is unexported. In my opinion both should be exported for flexibilities sake. Also in general having a public function take a private instance is bad practice.

**Comment by quantumew** [comment]
Ah I just noticed this https://github.com/okta/okta-sdk-golang/blob/da407cb0985399f7ce98bc06a6fecd00ef7a7482/okta/okta.go#L106. Could you update the docs to reflect this approach? I still think taking a private struct on a public function is not great but obviously a minor grievance now that I see this.

**Comment by bretterer** [comment]
Updated and will be in v2.0.0-rc.5
