### ISSUE TITLE
Fetch Applications from okta server fails through go-sdk

### ISSUE THREAD

**Issue by kundaliya** [okta/okta-sdk-golang#87]
The function ListApplications of okta package (okta/application.go:104) fails to fetch list of applications. It makes a GET request to /api/v1/apps for fetching list of application and tries to parse the response in []App which fails. It should parse it to []*Application and then typecast it to []App.
Reference code:
`client, _ := okta.NewClient(context.Background(), okta.WithOrgUrl("insertURLHere"), okta.WithToken("insertAPIKeyHere"), okta.WithCache(false)}) `
`qp := query.NewQueryParams(query.WithQ("insertAppNameHere"))`
`apps, _, err := oktaClient.Application.ListApplications(qp)`
Error Message:  `json: cannot unmarshal object into Go value of type okta.App`

**Comment by kundaliya** [comment]
Similar to #41

**Comment by rubyroobs** [comment]
@bretterer is there an ETA on when this will be fixed? We are an Enterprise Okta customer and this is causing a blocker on our integration. This is a core part of the SDK functionality (for us listing SAML applications) and it seems to be broken in all versions in the SDK.

**Comment by bretterer** [comment]
@rubyroobs - We will be updating the Golang SDK soon, and we will address these issues at that time.  

I do not have a definitive time this will be finished, so please keep an eye on this ticket for updates.

**Comment by kundaliya** [comment]
Hi @bretterer I wanted to check if you got a chance to get this fixed in v2? This is a simple issue happening because response is being unmarshalled into an interface instead of a struct. Also, when is v2 expected to be released?

**Comment by bretterer** [comment]
This has been addressed in v2 and should no longer be an issue. If you have any issues after updating, please open a new issue for us to look into
