### ISSUE TITLE
General Endpoint Generation Question

### ISSUE THREAD

**Issue by quantumew** [okta/okta-sdk-golang#88]
What is your stance on generating new endpoints for the SDK? Will this SDK ever cover Okta's entire API or are the currently missing endpoints intentionally missing? 

Related docs: https://github.com/okta/okta-sdk-golang#call-other-api-endpoints. 
For context the conversation started here: https://github.com/articulate/terraform-provider-okta/issues/269#issuecomment-528088591.

**Comment by bretterer** [comment]
@quantumew as of right now, we are only supporting the current endpoints, which is why we opened up the system to call your own endpoints. All of our endpoints we cover are generated via the openapi spec and we have strategically picked the endpoints with the most usage to start

**Comment by quantumew** [comment]
Thanks @bretterer! One more request if this is the case, can we expose doWithRetries on the request executor? If I was to make a request to a XML endpoint such as SAML app or IdP metadata endpoint, I could not use Do because it is hard coded to json. It would be nice not to have to rewrite the retry logic if possible. Either that or expose a separate function that handles XML.

**Comment by bretterer** [comment]
Hey @quantumew.  I have just released a [release candidate ](https://github.com/okta/okta-sdk-golang/releases/tag/v2.0.0-rc.1) for version 2.0.0 which includes all documented endpoints.  This also allows you to set the content type and accept headers during a call.  does this solve your issue?

**Comment by bretterer** [comment]
Closing this as stale.  If you are still experiencing an issue, please feel free to open a new issue and we will get back to you.
