### ISSUE TITLE
ListApplications will always fail to unmarshal from JSON

### ISSUE THREAD

**Issue by trevor403** [okta/okta-sdk-golang#97]
It seems that `ListApplications` will always fail at the unmarshal step in `buildResponse` due to the provided type being an interface rather than a struct. Even though the `App` interface can be implemented by an `Application` struct, this is not a helpful generic when doing JSON decoding.

https://github.com/okta/okta-sdk-golang/blob/v1.0.1/okta/application.go#L114

I suggest changing the calling scheme from using `[]App` to using `[]*Application`

**Comment by trevor403** [comment]
I have made an interim solution that supports returning an `[]App` type...
https://github.com/trevor403/okta-sdk-golang/commit/3ee0834818828a7ba9dfc29c8e8eca765e442b93

**Comment by trevor403** [comment]
I fixed an issue with Unmarshaling into an OpenID application struct, apparently the generator uses a struct type for openapi fields with type `string` and `enum` https://github.com/trevor403/okta-sdk-golang/commit/793d79436a5ca88707c7d031fb1642d809ec0561

These issues should really be fixed in the generator but I don't have the time to work on fixing that.

**Comment by bretterer** [comment]
@trevor403 In our pre-release for v2.0.0, this should be addressed.  It returns a list of `okta.Application` objects that you can then use to get the concrete type. 

https://github.com/okta/okta-sdk-golang/releases/tag/v2.0.0-rc.1

**Comment by trevor403** [comment]
Wonderful let's close this issue once a release is cut
